"""Pull everything the Huttons New Launch API has on one project, as the
starting kit for its website.

Usage:
  python3 scripts/huttons/pull-project.py "Project Name" [slug]

Writes, under src/features/selector/data/<slug>/:
  huttons-project.ts   facts: address, map position, district, segment,
                       tenure, developer, launch and completion, units,
                       and the developer's description, key points,
                       facilities and nearby amenities
  huttons-units.ts     every unit's block, stack, floor, floor plan, area,
                       availability, list and nett price (same format as
                       Thomson Reserve's, read by lib/listing.ts)
  huttons-media.ts     the floor plans, site plans and public images below
and downloads into public/<slug>/:
  plans/   one image per floor plan
  site/    site plan images, where the API has them
  images/  project images marked open to the public (sensitive = 1);
           internal-only media (sensitive = 0) is never fetched

Credentials come from HUTTONS_API_KEY and HUTTONS_API_SECRET. Agent contacts
are not fetched, and no PDFs are downloaded.
"""

import base64
import html
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import client  # noqa: E402

# TRM_ROOT redirects the output, for trying the script without touching the repo.
ROOT = Path(os.environ.get("TRM_ROOT") or Path(__file__).resolve().parents[2])


def text(v):
    """The API base64-encodes long text fields; decode them and drop HTML."""
    if not v:
        return None
    s = v
    try:
        decoded = base64.b64decode(v, validate=True).decode("utf-8")
        if decoded.strip():
            s = decoded
    except Exception:
        pass
    s = re.sub(r"<br\s*/?>|</p>|</li>", "\n", s, flags=re.I)
    s = html.unescape(re.sub(r"<[^>]+>", "", s))
    s = re.sub(r"\n\s*\n+", "\n", s).strip()
    return s or None


def download(url, dest):
    if not url:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        with urllib.request.urlopen(url, timeout=60) as r:
            dest.write_bytes(r.read())
        return dest
    except Exception as e:
        print("  could not download", url, "-", e)
        return None


def safe_name(s, i, ext=".jpg"):
    base = re.sub(r"[^A-Za-z0-9]+", "-", s or "").strip("-").lower() or f"item-{i}"
    return f"{base}{ext}"


def ext_of(url):
    m = re.search(r"\.(jpe?g|png|webp)(?:\?|$)", url or "", re.I)
    return "." + m.group(1).lower().replace("jpeg", "jpg") if m else ".jpg"


def ts(path, header, const, type_, value):
    path.write_text(f"""{header}

{type_}export const {const} = {json.dumps(value, indent=2, ensure_ascii=False)};
""")


def main(name, slug=None):
    found = client.get("project/queryProjectByPage", pageNo=1, pageSize=20, projectName=name)["lists"]
    project = next((p for p in found if p["projectName"].strip().lower() == name.strip().lower()), found[0] if found else None)
    if not project:
        raise SystemExit(f'No project called "{name}" in the Huttons New Launch API.')
    pid, slug = project["projectId"], slug or client.slugify(project["projectName"])
    data_dir, pub = ROOT / "src/features/selector/data" / slug, ROOT / "public" / slug
    data_dir.mkdir(parents=True, exist_ok=True)
    fetched = client.today()
    header = f"// Generated by scripts/huttons/pull-project.py from the Huttons New Launch API\n// on {fetched}. Don't edit by hand; run the script again to refresh."
    detail = client.get("project/queryProjectDetail", projectId=pid) or {}

    facts = {
        "source": "Huttons New Launch API",
        "fetched": fetched,
        "projectId": pid,
        "name": project["projectName"].strip(),
        "address": project.get("streetAddress") or None,
        "location": project.get("location") or detail.get("location") or None,
        "segment": detail.get("projectArea") or None,
        "latitude": float(project["latitude"]) if project.get("latitude") else None,
        "longitude": float(project["longitude"]) if project.get("longitude") else None,
        "tenure": project.get("tenure") or None,
        "developer": project.get("developer") or None,
        "totalUnits": int(float(project.get("unitsNum") or 0)) or None,
        "launchDate": client.day(project.get("launchDate")),
        "launchNote": project.get("launchDateAltText") or None,
        "completionDate": client.day(project.get("completionDate")),
        "description": text(detail.get("description")),
        "keyPoints": text(detail.get("keyPoints")),
        "facilities": text(detail.get("facilities")),
        "nearbyAmenities": text(detail.get("nearbyAmenities")),
    }
    ts(data_dir / "huttons-project.ts", header, "huttonsProject", "", facts)

    units = client.pages("unit/queryUnitsByPage", projectId=pid, orderType="stack")
    status = {"AVAILABLE": "available", "SOLD": "sold", "RESERVED": "reserved", "BOOKED": "reserved"}
    rows = []
    for u in units:
        block = (u.get("buildName") or "").split()[-1] if u.get("buildName") else ""
        price = lambda k: int(float(u[k])) if u.get(k) and float(u[k]) > 0 else None  # noqa: E731
        rows.append([block, u.get("stack"), int(float(u.get("floor") or 0)), u.get("floorPlanName"), round(float(u.get("area") or 0)),
                     status.get((u.get("purchaseStatus") or "").upper(), "pending"), price("price1"), price("price2")])
    rows.sort(key=lambda r: (str(r[0]).zfill(4), str(r[1]), r[2]))
    body = ",\n".join("    " + json.dumps(r, ensure_ascii=False) for r in rows)
    (data_dir / "huttons-units.ts").write_text(f"""{header}

import type {{ Listing, ListingUnit }} from "../../lib/listing";

export const huttonsSync: Listing & {{ projectName: string; launchDate: string | null; completionDate: string | null }} = {{
  source: "Huttons New Launch API",
  fetched: "{fetched}",
  projectName: {json.dumps(facts["name"])},
  launchDate: {json.dumps(facts["launchDate"])},
  completionDate: {json.dumps(facts["completionDate"])},
  units: [
{body},
  ] as ListingUnit[],
}};
""")

    media = {"floorPlans": [], "sitePlans": [], "images": []}
    for i, fp in enumerate(client.get("project/queryFloorPlan", projectId=pid) or []):
        f = download(fp.get("img"), pub / "plans" / safe_name(fp.get("floorPlanName"), i, ext_of(fp.get("img"))))
        if f:
            media["floorPlans"].append({"name": fp.get("floorPlanName"), "type": fp.get("floorPlanType"), "src": f"/{slug}/plans/{f.name}"})
    for i, sp in enumerate(client.get("project/querySitePlans", projectId=pid) or []):
        f = download(sp.get("img"), pub / "site" / safe_name(sp.get("sitePlanName"), i, ext_of(sp.get("img"))))
        if f:
            media["sitePlans"].append({"name": sp.get("sitePlanName"), "src": f"/{slug}/site/{f.name}"})
    skipped = 0
    for i, m in enumerate(client.get("project/queryProjectMedia", projectId=pid, type="Image") or []):
        if str(m.get("sensitive")) != "1":  # 0 = internal only
            skipped += 1
            continue
        f = download(m.get("url"), pub / "images" / safe_name(m.get("title") or m.get("id"), i, ext_of(m.get("url"))))
        if f:
            media["images"].append({"title": m.get("title") or None, "group": m.get("groupName") or None, "src": f"/{slug}/images/{f.name}"})
    media["credit"] = "Developer's marketing material, via the Huttons New Launch API. Renders are artist's impressions."
    ts(data_dir / "huttons-media.ts", header, "huttonsMedia", "", media)

    priced = sum(1 for r in rows if r[6] or r[7])
    print(f"{facts['name']} ({slug}): {len(rows)} units ({priced} priced), {len(media['floorPlans'])} floor plans, "
          f"{len(media['sitePlans'])} site plans, {len(media['images'])} public images ({skipped} internal-only skipped)")
    print(f"Next: follow docs/adding-a-project.md, starting from src/features/selector/data/{slug}/")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
