"""Pull the unit types still on sale at alternative projects, with the lowest
price and units left for each, from the Huttons New Launch API.

Usage:
  HUTTONS_API_KEY=... HUTTONS_API_SECRET=... \\
    python3 scripts/huttons/sync-alternatives.py OUT.ts "Lentor Gardens Residences" "Lentoria" ...

Writes a generated TypeScript file keyed by project name. Only unit types with
units still available are kept, with sizes and prices of those available
units. Shops are left out. Credentials come from the environment.
"""

import json
import re
import sys
import time
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
api = __import__("sync-project")  # token(), get() and SGT


def label(t):
    t = re.sub(r"\s+", " ", t.strip())
    t = re.sub(r"(?i)\b(\d) bedroom\b", r"\1BR", t)
    words = [w if w.isupper() and len(w) <= 3 or re.match(r"^\d", w) else w.capitalize() for w in re.split(r"(\s+|\+|\(|\))", t.lower())]
    out = "".join(words).replace("br", "BR").replace("Hs", "HS")
    return re.sub(r"\s*\+\s*", " + ", out).replace("( ", "(").replace(" )", ")")


def units(pid):
    rows, page = [], 1
    while True:
        for _ in range(4):
            try:
                d = api.get("unit/queryUnitsByPage", projectId=pid, pageNo=page, pageSize=200, orderType="stack")
                break
            except SystemExit:
                time.sleep(2)
        else:
            raise SystemExit(f"unit list failed for {pid}")
        rows += d["lists"]
        if len(rows) >= int(d["count"]) or not d["lists"]:
            return rows
        page += 1


def main(out, names):
    result = {}
    for name in names:
        found = api.get("project/queryProjectByPage", pageNo=1, pageSize=20, projectName=name)["lists"]
        p = next(x for x in found if x["projectName"].split(" ")[0].lower() == name.split(" ")[0].lower() and name.lower() in x["projectName"].lower())
        by_type = {}
        for u in units(p["projectId"]):
            if (u.get("type") or "").lower() == "shop" or not u.get("bedrooms"):
                continue
            by_type.setdefault(u["type"], []).append(u)
        types = []
        for t, us in by_type.items():
            av = [u for u in us if (u.get("purchaseStatus") or "").upper() == "AVAILABLE"]
            priced = [int(u.get("price2") or u.get("price1") or 0) for u in av]
            priced = [x for x in priced if x > 0]
            if not av:
                continue
            areas = [round(u["area"]) for u in av]
            types.append({"bedrooms": int(us[0]["bedrooms"]), "type": label(t), "sizeSqft": {"min": min(areas), "max": max(areas)},
                          "fromPrice": min(priced) if priced else None, "unitsLeft": len(av)})
        types.sort(key=lambda r: (r["bedrooms"], r["fromPrice"] or 9e12))
        result[name] = {"totalUnits": int(p.get("unitsNum") or 0) or None, "unitTypes": types}
    fetched = datetime.now(api.SGT).strftime("%Y-%m-%d")
    Path(out).write_text(f"""// Generated by scripts/huttons/sync-alternatives.py from the Huttons New Launch API
// on {fetched}. Don't edit by hand; run the script again to refresh.

import type {{ AlternativeUnitType }} from "../../model/project";

export const alternativesSync: {{ source: string; fetched: string; projects: Record<string, {{ totalUnits: number | null; unitTypes: AlternativeUnitType[] }}> }} = {{
  source: "Huttons New Launch API",
  fetched: "{fetched}",
  projects: {json.dumps(result, indent=2, ensure_ascii=False)},
}};
""")
    for n, r in result.items():
        print(n, len(r["unitTypes"]), "types on sale")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2:])
