"""Pull a project's latest units, availability and prices from the Huttons
New Launch API (api.singmap.com) into a generated TypeScript file.

Usage:
  HUTTONS_API_KEY=... HUTTONS_API_SECRET=... \\
    python3 scripts/huttons/sync-project.py "Thomson Reserve" \\
    src/features/selector/data/thomson-reserve/huttons-units.ts

The key and secret are read from the environment and never written out.
Only factual unit data is kept: block, stack, floor, floor plan, area,
availability, list price and nett price. Agent contacts and internal media
are not fetched. Needs network access to api.singmap.com.
"""

import hashlib
import json
import os
import sys
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone

HOST = "https://api.singmap.com/cgi-api"
SGT = timezone(timedelta(hours=8))


def token():
    key, secret = os.environ.get("HUTTONS_API_KEY"), os.environ.get("HUTTONS_API_SECRET")
    if not key or not secret:
        raise SystemExit("Set HUTTONS_API_KEY and HUTTONS_API_SECRET.")
    q = urllib.parse.urlencode({"key": key, "secret": secret})
    r = json.load(urllib.request.urlopen(urllib.request.Request(f"{HOST}/token?{q}", data=b"", method="POST"), timeout=30))
    return r["datas"]["access_token"]


def get(path, **params):
    t = token()  # tokens last 5 minutes, so take a fresh one per call
    rt = datetime.now(SGT).strftime("%Y%m%d%H%M%S")
    q = {"token": t, "request_time": rt, "sign": hashlib.md5((t + rt).encode()).hexdigest(), **params}
    r = json.load(urllib.request.urlopen(f"{HOST}/{path}?" + urllib.parse.urlencode(q), timeout=60))
    if str(r.get("code")) != "0":
        raise SystemExit(f"{path}: {r.get('msg')}")
    return r.get("datas")


def day(ms):
    return datetime.fromtimestamp(int(ms) / 1000, SGT).strftime("%Y-%m-%d") if ms else None


def main(name, out):
    found = get("project/queryProjectByPage", pageNo=1, pageSize=20, projectName=name)["lists"]
    project = next(p for p in found if p["projectName"].lower() == name.lower())
    pid = project["projectId"]
    units, page = [], 1
    while True:
        d = get("unit/queryUnitsByPage", projectId=pid, pageNo=page, pageSize=200, orderType="stack")
        units += d["lists"]
        if len(units) >= int(d["count"]) or not d["lists"]:
            break
        page += 1
    status = {"AVAILABLE": "available", "SOLD": "sold", "RESERVED": "reserved", "BOOKED": "reserved"}
    rows = []
    # Blocks are usually numbers ("Blk 5"), but some projects name tower sections, e.g. "(L4-L16)".
    def block_key(u):
        b = u["buildName"].split()[-1]
        return (0, int(b), "") if b.isdigit() else (1, 0, b)

    for u in sorted(units, key=lambda u: (block_key(u), u["stack"], int(u["floor"]))):
        price = lambda k: int(u[k]) if u.get(k) and float(u[k]) > 0 else None
        rows.append([u["buildName"].split()[-1], u["stack"], int(u["floor"]), u["floorPlanName"], round(u["area"] or 0),
                     status.get((u["purchaseStatus"] or "").upper(), "pending"), price("price1"), price("price2")])
    fetched = datetime.now(SGT).strftime("%Y-%m-%d")
    body = ",\n".join("    " + json.dumps(r, ensure_ascii=False) for r in rows)
    with open(out, "w") as f:
        f.write(f"""// Generated by scripts/huttons/sync-project.py from the Huttons New Launch API
// on {fetched}. Don't edit by hand; run the script again to refresh.

import type {{ Listing, ListingUnit }} from "../../lib/listing";

export const huttonsSync: Listing & {{ projectName: string; launchDate: string | null; completionDate: string | null }} = {{
  source: "Huttons New Launch API",
  fetched: "{fetched}",
  projectName: {json.dumps(project["projectName"])},
  launchDate: {json.dumps(day(project.get("launchDate")))},
  completionDate: {json.dumps(day(project.get("completionDate")))},
  units: [
{body},
  ] as ListingUnit[],
}};
""")
    priced = sum(1 for r in rows if r[6] or r[7])
    print(f"{len(rows)} units, {priced} priced, written to {out}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
