// Generated by scripts/huttons/pull-project.py from the Huttons New Launch API
// on 2026-10-05. Don't edit by hand; run the script again to refresh.

export const huttonsMedia = {
  "floorPlans": [
    {
      "name": "D2",
      "type": "4 BEDROOM",
      "src": "/the-serra-residences/plans/d2.png"
    },
    {
      "name": "C2",
      "type": "3 BEDROOM",
      "src": "/the-serra-residences/plans/c2.png"
    },
    {
      "name": "D3",
      "type": "4 BEDROOM + STUDY",
      "src": "/the-serra-residences/plans/d3.png"
    },
    {
      "name": "C1",
      "type": "3 BEDROOM",
      "src": "/the-serra-residences/plans/c1.png"
    },
    {
      "name": "D4",
      "type": "4 BEDROOM PREMIUM WITH PRIVATE LIFT",
      "src": "/the-serra-residences/plans/d4.png"
    },
    {
      "name": "B2",
      "type": "2 BEDROOM + STUDY",
      "src": "/the-serra-residences/plans/b2.png"
    },
    {
      "name": "E",
      "type": "5 BEDROOM PREMIUM WITH PRIVATE LIFT",
      "src": "/the-serra-residences/plans/e.png"
    },
    {
      "name": "C3",
      "type": "3 BEDROOM",
      "src": "/the-serra-residences/plans/c3.png"
    },
    {
      "name": "D1",
      "type": "4 BEDROOM",
      "src": "/the-serra-residences/plans/d1.png"
    },
    {
      "name": "PH2",
      "type": "PENTHOUSE",
      "src": "/the-serra-residences/plans/ph2.png"
    },
    {
      "name": "B1",
      "type": "2 BEDROOM + STUDY",
      "src": "/the-serra-residences/plans/b1.png"
    },
    {
      "name": "PH1",
      "type": "PENTHOUSE",
      "src": "/the-serra-residences/plans/ph1.png"
    },
    {
      "name": "B1a",
      "type": "2 BEDROOM + STUDY",
      "src": "/the-serra-residences/plans/b1a.png"
    }
  ],
  "sitePlans": [
    {
      "name": "Elevation Chart",
      "src": "/the-serra-residences/site/elevation-chart.png"
    },
    {
      "name": "Site Plan",
      "src": "/the-serra-residences/site/site-plan.jpg"
    }
  ],
  "images": [],
  "credit": "Developer's marketing material, via the Huttons New Launch API. Renders are artist's impressions."
};
