// Generated by scripts/huttons/nearby-projects.py from the new launches map's
// catalogue (Huttons New Launch API, 2026-10-05). Don't edit by hand; run the
// script again after sync-catalogue.py to refresh.

import type { NearbySync } from "../nearby";

export const nearbySync: NearbySync = {
  "source": "Huttons New Launch API",
  "fetched": "2026-10-05",
  "rule": "The four nearest projects on the new launches map (launched 2020 or later), by straight-line distance between map positions, that still have units for sale (or have not launched yet) in a bedroom type this project also offers.",
  "projects": [
    {
      "id": "828a0cc539e54e7e90dcaee7e5c1f995",
      "slug": "the-ranz",
      "name": "The Ranz",
      "km": 1.13,
      "district": "D08",
      "address": "109 Rangoon Road",
      "segment": "RCR",
      "developer": "Kefi Development Pte. Ltd.",
      "tenure": "Freehold",
      "totalUnits": 17,
      "completion": "2025-10-31",
      "launchDate": "2024-12-31",
      "mrt": {
        "name": "Farrer Park",
        "metres": 345,
        "minutes": 6
      },
      "image": "nearby-the-ranz.jpg",
      "unitTypes": [
        {
          "bedrooms": 2,
          "type": "2BR + Study",
          "sizeSqft": {
            "min": 689,
            "max": 775
          },
          "fromPrice": 1681000,
          "fromPsf": 2296,
          "psfRange": {
            "min": 2296,
            "max": 2389,
            "avg": 2350,
            "units": 3
          },
          "unitsLeft": 3
        }
      ]
    },
    {
      "id": "81f063c801ef487f8a695b825e20c30c",
      "slug": "the-arcady-at-boon-keng",
      "name": "The Arcady at Boon Keng",
      "km": 1.78,
      "district": "D12",
      "address": "1037 Serangoo Rd",
      "segment": "RCR",
      "developer": "KSH Holdings Ultra Unity(JV)",
      "tenure": "Freehold",
      "totalUnits": 172,
      "completion": "2028-12-31",
      "launchDate": "2024-01-20",
      "mrt": {
        "name": "Boon Keng",
        "metres": 522,
        "minutes": 8
      },
      "image": "nearby-the-arcady-at-boon-keng.jpg",
      "unitTypes": [
        {
          "bedrooms": 2,
          "type": "2BR",
          "sizeSqft": {
            "min": 667,
            "max": 678
          },
          "fromPrice": 2074000,
          "fromPsf": 3059,
          "psfRange": {
            "min": 3059,
            "max": 3071,
            "avg": 3065,
            "units": 2
          },
          "unitsLeft": 2
        },
        {
          "bedrooms": 2,
          "type": "2BR + Study",
          "sizeSqft": {
            "min": 764,
            "max": 764
          },
          "fromPrice": 2149000,
          "fromPsf": 2813,
          "psfRange": {
            "min": 2813,
            "max": 3090,
            "avg": 2966,
            "units": 21
          },
          "unitsLeft": 21
        },
        {
          "bedrooms": 3,
          "type": "3BR Premium",
          "sizeSqft": {
            "min": 1087,
            "max": 1195
          },
          "fromPrice": 2963000,
          "fromPsf": 2726,
          "psfRange": {
            "min": 2715,
            "max": 2924,
            "avg": 2808,
            "units": 18
          },
          "unitsLeft": 18
        },
        {
          "bedrooms": 3,
          "type": "3BR Premium + Study",
          "sizeSqft": {
            "min": 1281,
            "max": 1496
          },
          "fromPrice": 3471000,
          "fromPsf": 2710,
          "psfRange": {
            "min": 2710,
            "max": 2932,
            "avg": 2801,
            "units": 10
          },
          "unitsLeft": 10
        },
        {
          "bedrooms": 4,
          "type": "Penthouse",
          "sizeSqft": {
            "min": 2433,
            "max": 2583
          },
          "fromPrice": 8117000,
          "fromPsf": 3336,
          "psfRange": {
            "min": 3329,
            "max": 3336,
            "avg": 3332,
            "units": 2
          },
          "unitsLeft": 2
        }
      ]
    },
    {
      "id": "23a0bd1f430c4d55a8bf6fd39fb177b8",
      "slug": "the-orie",
      "name": "The Orie",
      "km": 1.89,
      "district": "D12",
      "address": "10 , 12 Lorong 1 Toa Payoh\n",
      "segment": "RCR",
      "developer": "TRANSCEND RESIDENTIAL (TOA PAYOH) PTE. LTD",
      "tenure": "99 Years",
      "totalUnits": 777,
      "completion": "2028-06-30",
      "launchDate": "2025-01-18",
      "mrt": {
        "name": "Braddell",
        "metres": 761,
        "minutes": 11
      },
      "image": "nearby-the-orie.jpg",
      "unitTypes": [
        {
          "bedrooms": 3,
          "type": "3BR Dual Key",
          "sizeSqft": {
            "min": 1130,
            "max": 1130
          },
          "fromPrice": 3024000,
          "fromPsf": 2676,
          "psfRange": {
            "min": 2676,
            "max": 2744,
            "avg": 2703,
            "units": 6
          },
          "unitsLeft": 6
        }
      ]
    },
    {
      "id": "01f112d7a2474e0683f8adfabe8ce9a0",
      "slug": "duet-emily",
      "name": "Duet @ Emily",
      "km": 2.11,
      "district": "D09",
      "address": "2,4,6 Mount Emily Road",
      "segment": "CCR",
      "developer": "ZACD PROPERTY PTE. LTD.",
      "tenure": "Freehold",
      "totalUnits": 20,
      "completion": "2028-12-31",
      "launchDate": "2026-06-27",
      "mrt": {
        "name": "Rochor",
        "metres": 534,
        "minutes": 8
      },
      "image": "nearby-duet-emily.jpg",
      "unitTypes": [
        {
          "bedrooms": 2,
          "type": "2BR Executive",
          "sizeSqft": {
            "min": 549,
            "max": 549
          },
          "fromPrice": 1401000,
          "fromPsf": 2552,
          "psfRange": {
            "min": 2552,
            "max": 2867,
            "avg": 2757,
            "units": 4
          },
          "unitsLeft": 4
        },
        {
          "bedrooms": 2,
          "type": "2BR Deluxe",
          "sizeSqft": {
            "min": 667,
            "max": 678
          },
          "fromPrice": 1726000,
          "fromPsf": 2546,
          "psfRange": {
            "min": 2546,
            "max": 2780,
            "avg": 2701,
            "units": 4
          },
          "unitsLeft": 4
        },
        {
          "bedrooms": 2,
          "type": "2BR Premium",
          "sizeSqft": {
            "min": 667,
            "max": 850
          },
          "fromPrice": 1812000,
          "fromPsf": 2717,
          "psfRange": {
            "min": 2717,
            "max": 2748,
            "avg": 2732,
            "units": 2
          },
          "unitsLeft": 2
        },
        {
          "bedrooms": 2,
          "type": "2BR Loft",
          "sizeSqft": {
            "min": 936,
            "max": 1335
          },
          "fromPrice": 2468000,
          "fromPsf": 2637,
          "psfRange": {
            "min": 2568,
            "max": 2637,
            "avg": 2602,
            "units": 2
          },
          "unitsLeft": 2
        }
      ]
    }
  ]
};
