// Generated by scripts/huttons/nearby-projects.py from the new launches map's
// catalogue (Huttons New Launch API, 2026-10-05). Don't edit by hand; run the
// script again after sync-catalogue.py to refresh.

import type { NearbySync } from "../nearby";

export const nearbySync: NearbySync = {
  "source": "Huttons New Launch API",
  "fetched": "2026-10-05",
  "rule": "The four nearest projects on the new launches map, by straight-line distance between map positions, that still have units for sale (or have not launched yet) in a bedroom type this project also offers.",
  "projects": [
    {
      "id": "2e12d01c73fc4def9f4926f3221cae27",
      "slug": "lucida",
      "name": "Lucida",
      "km": 1.03,
      "district": "D11",
      "address": "2 Suffolk Rd",
      "segment": "CCR",
      "developer": "Novelty Organisation Pte Ltd",
      "tenure": "Freehold",
      "totalUnits": 62,
      "completion": "2011-12-31",
      "launchDate": "2008-02-28",
      "mrt": {
        "name": "Novena",
        "metres": 1130,
        "minutes": 17
      },
      "image": "nearby-lucida.jpg",
      "unitTypes": [
        {
          "bedrooms": 4,
          "type": "4BR",
          "sizeSqft": {
            "min": 3854,
            "max": 4176
          },
          "fromPrice": 6750000,
          "fromPsf": 1616,
          "psfRange": {
            "min": 1616,
            "max": 1616,
            "avg": 1616,
            "units": 1
          },
          "unitsLeft": 1
        }
      ]
    },
    {
      "id": "828a0cc539e54e7e90dcaee7e5c1f995",
      "slug": "the-ranz",
      "name": "The Ranz",
      "km": 1.13,
      "district": "D08",
      "address": "109 Rangoon Road",
      "segment": "RCR",
      "developer": "Kefi Development Pte. Ltd.",
      "tenure": "Freehold",
      "totalUnits": 17,
      "completion": "2025-10-31",
      "launchDate": "2024-12-31",
      "mrt": {
        "name": "Farrer Park",
        "metres": 345,
        "minutes": 6
      },
      "image": "nearby-the-ranz.jpg",
      "unitTypes": [
        {
          "bedrooms": 2,
          "type": "2BR + Study",
          "sizeSqft": {
            "min": 689,
            "max": 775
          },
          "fromPrice": 1681000,
          "fromPsf": 2296,
          "psfRange": {
            "min": 2296,
            "max": 2389,
            "avg": 2350,
            "units": 3
          },
          "unitsLeft": 3
        }
      ]
    },
    {
      "id": "81f063c801ef487f8a695b825e20c30c",
      "slug": "the-arcady-at-boon-keng",
      "name": "The Arcady at Boon Keng",
      "km": 1.78,
      "district": "D12",
      "address": "1037 Serangoo Rd",
      "segment": "RCR",
      "developer": "KSH Holdings Ultra Unity(JV)",
      "tenure": "Freehold",
      "totalUnits": 172,
      "completion": "2028-12-31",
      "launchDate": "2024-01-20",
      "mrt": {
        "name": "Boon Keng",
        "metres": 522,
        "minutes": 8
      },
      "image": "nearby-the-arcady-at-boon-keng.jpg",
      "unitTypes": [
        {
          "bedrooms": 2,
          "type": "2BR",
          "sizeSqft": {
            "min": 667,
            "max": 678
          },
          "fromPrice": 2074000,
          "fromPsf": 3059,
          "psfRange": {
            "min": 3059,
            "max": 3071,
            "avg": 3065,
            "units": 2
          },
          "unitsLeft": 2
        },
        {
          "bedrooms": 2,
          "type": "2BR + Study",
          "sizeSqft": {
            "min": 764,
            "max": 764
          },
          "fromPrice": 2149000,
          "fromPsf": 2813,
          "psfRange": {
            "min": 2813,
            "max": 3090,
            "avg": 2966,
            "units": 21
          },
          "unitsLeft": 21
        },
        {
          "bedrooms": 3,
          "type": "3BR Premium",
          "sizeSqft": {
            "min": 1087,
            "max": 1195
          },
          "fromPrice": 2963000,
          "fromPsf": 2726,
          "psfRange": {
            "min": 2715,
            "max": 2924,
            "avg": 2808,
            "units": 18
          },
          "unitsLeft": 18
        },
        {
          "bedrooms": 3,
          "type": "3BR Premium + Study",
          "sizeSqft": {
            "min": 1281,
            "max": 1496
          },
          "fromPrice": 3471000,
          "fromPsf": 2710,
          "psfRange": {
            "min": 2710,
            "max": 2932,
            "avg": 2801,
            "units": 10
          },
          "unitsLeft": 10
        },
        {
          "bedrooms": 4,
          "type": "Penthouse",
          "sizeSqft": {
            "min": 2433,
            "max": 2583
          },
          "fromPrice": 8117000,
          "fromPsf": 3336,
          "psfRange": {
            "min": 3329,
            "max": 3336,
            "avg": 3332,
            "units": 2
          },
          "unitsLeft": 2
        }
      ]
    },
    {
      "id": "2944874e9285475194bd3209b67643be",
      "slug": "reignwood-hamilton-scotts",
      "name": "Reignwood Hamilton Scotts",
      "km": 1.87,
      "district": "D09",
      "address": "37 Scotts Rd",
      "segment": "CCR",
      "developer": "Sardinia Properties Pte Ltd",
      "tenure": "Freehold",
      "totalUnits": 56,
      "completion": "2012-06-30",
      "launchDate": "2008-08-08",
      "mrt": {
        "name": "Newton",
        "metres": 298,
        "minutes": 5
      },
      "image": "nearby-reignwood-hamilton-scotts.jpg",
      "unitTypes": [
        {
          "bedrooms": 3,
          "type": "3BR",
          "sizeSqft": {
            "min": 2756,
            "max": 2756
          },
          "fromPrice": 10038000,
          "fromPsf": 3642,
          "psfRange": {
            "min": 3642,
            "max": 3780,
            "avg": 3714,
            "units": 3
          },
          "unitsLeft": 4
        },
        {
          "bedrooms": 3,
          "type": "Junior Penthouse",
          "sizeSqft": {
            "min": 3229,
            "max": 3229
          },
          "fromPrice": null,
          "fromPsf": null,
          "psfRange": null,
          "unitsLeft": 1
        },
        {
          "bedrooms": 5,
          "type": "Penthouse",
          "sizeSqft": {
            "min": 6975,
            "max": 6975
          },
          "fromPrice": null,
          "fromPsf": null,
          "psfRange": null,
          "unitsLeft": 2
        }
      ]
    }
  ]
};
