// Generated by scripts/huttons/build-sites.py: every project with an
// automatically built mini site. Don't edit by hand; run
// `python3 scripts/huttons/build-sites.py --registry` after adding a trace.

export interface AutoListing {
  id: string;
  name: string;
  district: string | null;
  area: string | null;
  summary: string;
  image: string | null;
  traced: boolean;
}

export const autoListings: AutoListing[] = [
  {
    "id": "21-anderson",
    "name": "21 Anderson",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "18 units · Freehold · D10",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/b87e1770aeeb4edaa5927143b6cebe0c/imgs/20250304/c32631e3594b49ee8f9689cdc0808101.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "26-newton",
    "name": "26 Newton",
    "district": "D11",
    "area": "Newton / Novena",
    "summary": "180 units · Freehold · D11",
    "image": "https://img.singmap.com/upload/broke/19541e9bb12d48e7a172283c3f52008f/3a4782498bdd46bfaf5a31d2a6c02776/imgs/20241209/b6d1a28e7f564dacb9fe336220fc4364.jpg?quality=50",
    "traced": false
  },
  {
    "id": "8-bt",
    "name": "8@BT",
    "district": "D21",
    "area": "Clementi / Upper Bukit Timah",
    "summary": "158 units · 99 Years · D21",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/00a420908c8249778e11c7d2259afb18/imgs/20240830/7c3b1ed93cd54e8297e14c44214c58fc.jpg?quality=50",
    "traced": true
  },
  {
    "id": "amberwood-at-holland",
    "name": "Amberwood At Holland",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "212 units · 99 Years · D10",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/a1bec73dbfd74619848faf3e0c5090c9/imgs/20260813/edc3db0b9dff4361b9586fe1bf34c11d.png?quality=50",
    "traced": true
  },
  {
    "id": "arc-380",
    "name": "ARC 380",
    "district": "D08",
    "area": "Farrer Park / Serangoon Road",
    "summary": "154 units · Freehold · D08",
    "image": "https://img.singmap.com/upload/broke/43f80b9550a14e999f55c9913445741e/b1d3d9c5b6624a59aa8158137c26f94f/imgs/20260205/065821f5f44e4e2eb32b627004ce0f13.jpg?quality=50",
    "traced": false
  },
  {
    "id": "ardor-residence",
    "name": "Ardor Residence",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "35 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/6f49cb825a99471b89c7982903ad033f/a03af76f6a3649c0b3ca682177b03622/imgs/20240108/245715f386264a61bf85d6bf77367e3c.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "arina-east-residences",
    "name": "Arina East Residences",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "107 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/f8b877eb3d354bdfa56ef5b1b60924ca/imgs/20240919/7007c7ee02674b2c92fa39f9ce57cd00.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "artisan-8",
    "name": "Artisan 8",
    "district": "D20",
    "area": "Ang Mo Kio / Bishan / Thomson",
    "summary": "38 units · Freehold · D20",
    "image": "https://img.singmap.com/upload/broke/1557b87be48b40c491095353fd85307c/3086823b425e4aaa81b23c040747a924/imgs/20250514/d6cdf960e14d4ad0be1c949e57abd129.jpg?quality=50",
    "traced": false
  },
  {
    "id": "atlassia",
    "name": "Atlassia",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "39 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/d0cc32d4726b49e395146ed9c349dcdf/imgs/20260817/05ccdc51bd30446b9c5012118e111c8e.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "aurea",
    "name": "Aurea",
    "district": "D07",
    "area": "Beach Road / Bugis / Rochor",
    "summary": "188 units · 99 Years · D07",
    "image": "https://img.singmap.com/upload/broke/2bb941dfc39445998b241147df411af3/c2cf5c2178c5433fb6eb56cbe2dfbb3d/imgs/20250310/f5a9ad9a6c6044ba95358713592b8b3a.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "bagnall-haus",
    "name": "Bagnall Haus",
    "district": "D16",
    "area": "Bedok / Upper East Coast",
    "summary": "113 units · Freehold · D16",
    "image": "https://img.singmap.com/upload/broke/e08e357f9f884accb9c10bc4de0c8c3a/d628a74456874b778432799fd9e53517/imgs/20241118/e8c0eb6c817d4c9ca6c0d535451f9ba2.png?quality=50",
    "traced": true
  },
  {
    "id": "bedok-rise-gls",
    "name": "Bedok Rise GLS",
    "district": "D16",
    "area": "Bedok / Upper East Coast",
    "summary": "Freehold · D16",
    "image": "https://img.singmap.com/upload/broke/22e794e47aae4f7da8a230195f30e7a1/0855eefe285a456783eeda789a0203cf/imgs/20260907/10c2797ce17c44709294cafc231ee91f.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "belgravia-ace",
    "name": "Belgravia Ace",
    "district": "D28",
    "area": "Seletar / Yio Chu Kang",
    "summary": "107 units · Freehold · D28",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/6527d3d2d1724fdc965f655766848e9e/imgs/20260812/f436fc7b385847f2832795cc6ff11e0b.JPG?quality=50",
    "traced": false
  },
  {
    "id": "bloomsbury-residences",
    "name": "Bloomsbury Residences",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "358 units · 99 Years · D05",
    "image": "https://img.singmap.com/upload/broke/de0b7f8e27dc4ad0a99ac8a53c792778/2546baa1d7364ff1b2024aa98c49a248/imgs/20250314/c9b50793f8c1413c80f9023a7c1d11be.png?quality=50",
    "traced": true
  },
  {
    "id": "canberra-crescent-residences",
    "name": "Canberra Crescent Residences",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "376 units · 99 years · D27",
    "image": "https://img.singmap.com/upload/broke/ccebe384b5234eec8b78e66325fa7c43/697564dce09a4511a8d56e739ecdaabd/imgs/20250619/052d47077927438893cefc3828f64721.png?quality=50",
    "traced": true
  },
  {
    "id": "canninghill-piers",
    "name": "Canninghill Piers",
    "district": "D06",
    "area": "City Hall / Clarke Quay",
    "summary": "696 units · 99 Years · D06",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/227b5a5863fa4631875adcfb07b38cae/imgs/280898b9a6324cafb927c7317ba81e44.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "cape-royale",
    "name": "Cape Royale",
    "district": "D04",
    "area": "/ SOUTHERN ISLANDS",
    "summary": "255 units · 99 YEARS · D04",
    "image": "https://img.singmap.com/upload/broke/44f3ed51657e4cea84784fcb81030365/28d43ed6d0b6482297214f731c84dd63/imgs/20220614/c4f406761b7741b7b62d44d169857157.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "cecil-place",
    "name": "CECIL PLACE",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "28 units · Freehold · D01",
    "image": "https://img.singmap.com/upload/broke/a5684cb2db2442fdb1984b2d690173e3/e409b14a685243cb85d6e07214f46b31/imgs/20250714/b403dbd79bad465a97a3f804c94d84c4.png?quality=50",
    "traced": false
  },
  {
    "id": "centrium-square",
    "name": "Centrium Square",
    "district": "D08",
    "area": "Farrer Park / Serangoon Road",
    "summary": "145 units · Freehold · D08",
    "image": "https://img.singmap.com/upload/broke/43f80b9550a14e999f55c9913445741e/885368e74a04434e9b3b946641dcbc34/imgs/6c5b98b165a0448d9335fac8a9bfa1af.jpg?quality=50",
    "traced": false
  },
  {
    "id": "chancery-hill-collection",
    "name": "Chancery Hill Collection",
    "district": "D11",
    "area": "Newton / Novena",
    "summary": "8 units · Freehold · D11",
    "image": "https://img.singmap.com/upload/broke/5999208594424323b957c1cb2e1d2052/dd37874339b244c081bcfa12cafa938d/imgs/20260707/7c2af0f73a9e4c9c8dcc97d69da1920b.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "chencharu-close-gls",
    "name": "Chencharu Close GLS",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "99 Years · D27",
    "image": "https://img.singmap.com/upload/broke/21f1bbb880494513b71eab1b7bc0393c/a8dc1c7b80914f65a5c07128aaa9e777/imgs/20251030/4ab956a847254ab4abb3be7cc3e0e8ed.png?quality=50",
    "traced": false
  },
  {
    "id": "chuan-park",
    "name": "Chuan Park",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "916 units · 99 Years · D19",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/eccc7150c2254954a2371b9655eb459c/imgs/20240929/2a00a5437f3e4912a60a1b3fb12cbc75.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "citrine-foodland",
    "name": "Citrine Foodland",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "16 units · Freehold · D19",
    "image": "https://img.singmap.com/upload/broke/dcde6a952bc14db18be5f37480b71fbb/57c40296d6474c88806a1fef94655fa4/imgs/4b7fcf1525ac437cb9483991d42ffd54.jpg?quality=50",
    "traced": false
  },
  {
    "id": "clovelle-of-woodlands",
    "name": "Clovelle of Woodlands",
    "district": "D25",
    "area": "Admiralty / Woodlands",
    "summary": "99 Years · D25",
    "image": "https://img.singmap.com/upload/broke/347d7de60c1c4728ba7d01ee6ffdc5f8/679021ecbcab48be90b64e16e77b82b7/imgs/20260511/eccc703a1c98440f86a78f0d21680651.png?quality=50",
    "traced": false
  },
  {
    "id": "coastal-cabana",
    "name": "Coastal Cabana",
    "district": "D17",
    "area": "Loyang / Changi",
    "summary": "748 units · 99 years · D17",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/60dab94999134e819496275b30b239aa/imgs/20251117/4fcc4ebc0fb446f5aac1c0e2509c25e6.jpg?quality=50",
    "traced": true
  },
  {
    "id": "ct-foodnex",
    "name": "CT FoodNEX",
    "district": "D26",
    "area": "Mandai / Upper Thomson",
    "summary": "110 units · Freehold · D26",
    "image": "https://img.singmap.com/upload/broke/e6af41ced1144d5abb60b7d13bff431c/b136ebee90cf434e9212dc4f115625f9/imgs/20230424/4ff2ebc19439487d8f5479b264e520c8.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "ct-gold-macpherson",
    "name": "CT GOLD @ MACPHERSON",
    "district": "D13",
    "area": "Macpherson / Potong Pasir",
    "summary": "66 units · Freehold · D13",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/f7aadbfa0e1f4b74a3c19816da50f3e0/imgs/20260304/297ab86f030a40268c193b313ab9a5a9.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "dairy-farm-walk-gls",
    "name": "Dairy Farm Walk GLS",
    "district": "D23",
    "area": "Bukit Batok / Bukit Panjang",
    "summary": "99 Years · D23",
    "image": "https://img.singmap.com/upload/broke/e08e357f9f884accb9c10bc4de0c8c3a/cf6fa6bd96944f56ae7ea4d8bdb162cd/imgs/20260123/dfb54fcd853c442ca4151375b44bacfc.png?quality=50",
    "traced": false
  },
  {
    "id": "duet-emily",
    "name": "Duet @ Emily",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "20 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/18b5304434154c31add8ac44e89f9a82/01f112d7a2474e0683f8adfabe8ce9a0/imgs/20260409/f487baaba78c4322af98b391afb817ed.jpg?quality=50",
    "traced": true
  },
  {
    "id": "dunearn-house",
    "name": "Dunearn House .",
    "district": "D11",
    "area": "Newton / Novena",
    "summary": "380 units · 99 Years · D11",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/700527d89a91474a8887269b36cb1642/imgs/20260703/1e55386c09b74ccf8b5e2e1259ce0f5d.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "eden-residences-capitol",
    "name": "Eden Residences Capitol",
    "district": "D06",
    "area": "City Hall / Clarke Quay",
    "summary": "39 units · 99 Years · D06",
    "image": "https://img.singmap.com/upload/broke/249a12907cb94581bbf2093c1efdbb27/72abedb363474234814fc92c4fd2ea90/imgs/a0de07f1e999498a834d26e29096ede1.jpg?quality=50",
    "traced": false
  },
  {
    "id": "elta",
    "name": "ELTA",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "501 units · 99 Years · D05",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/88a853a0ae6443749b7e5f957b8e6480/imgs/20241206/bfd506307b5f4f8b9180c6a0156af646.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "faber-residence",
    "name": "Faber Residence",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "399 units · 99 years · D05",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/946c32a7bc3c43f6b1df4513a33d371e/imgs/20250919/58ea0426fe534b1bb6d527cbd11981c8.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "forett-at-bukit-timah",
    "name": "Forett At Bukit Timah",
    "district": "D21",
    "area": "Clementi / Upper Bukit Timah",
    "summary": "635 units · Freehold · D21",
    "image": "https://img.singmap.com/upload/broke/de0b7f8e27dc4ad0a99ac8a53c792778/3c4e53308b2c48d0bca49a3984e36eaa/imgs/edb55fa8ec5b488ba990fde93557ec4e.png?quality=50",
    "traced": true
  },
  {
    "id": "gate",
    "name": "GATE+",
    "district": "D22",
    "area": "Boon Lay / Jurong / Tuas",
    "summary": "268 units · 33 years Leasehold · D22",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/e6811dbb52f34300b47cbf03d976cbac/imgs/20260331/a970e6c3fd234b179631c19ff178b046.png?quality=50",
    "traced": false
  },
  {
    "id": "gems-ville",
    "name": "Gems Ville",
    "district": "D14",
    "area": "Eunos / Geylang / Paya Lebar",
    "summary": "24 units · Freehold · D14",
    "image": "https://img.singmap.com/upload/broke/a9a01cbb4f6f4db1abb85b4c1b314e0e/33e2df04dc4b4e3c8bb0d6c780ffdc89/imgs/20230107/5450d41271004bb6935f59ea178c16cd.png?quality=50",
    "traced": true
  },
  {
    "id": "gourmet-xchange",
    "name": "Gourmet Xchange",
    "district": "D13",
    "area": "Macpherson / Potong Pasir",
    "summary": "273 units · 33 Years · D13",
    "image": "https://img.singmap.com/upload/broke/26a7e3532c1e40c493ccd4d1302549f3/f387d063c6b84ee7837c5c9d4a0582d5/imgs/20260115/9ccd2f3a47aa4cfc8d5080567bbb7b9a.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "grand-dunman",
    "name": "Grand Dunman",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "1,008 units · 99 Years · D15",
    "image": "https://img.singmap.com/upload/broke/70c2bd829c564c96a51d0ee8656dc810/1430cfcb8f9c4302860203c0f370a169/imgs/20230627/f80f22615fe14629bb8eade4a1907730.jpg?quality=50",
    "traced": true
  },
  {
    "id": "grange-1866",
    "name": "Grange 1866",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "60 units · Freehold · D10",
    "image": "https://img.singmap.com/upload/broke/3cf67b55b38146f3ae0cb7c5c62248b8/9e6984905b7540529ae6a9e4e1e959a1/imgs/8e4e16a04ffd47228bdf6ec0923aa826.jpg?quality=50",
    "traced": false
  },
  {
    "id": "harrison-food-building",
    "name": "Harrison Food Building",
    "district": "D13",
    "area": "Macpherson / Potong Pasir",
    "summary": "43 units · Freehold · D13",
    "image": "https://img.singmap.com/upload/broke/b33f6b122cf24952a13e5cb46910c61b/21247817bd51435aa3186d19054e6931/imgs/20241009/66adfb01468e4701b12cdbe36198c9c7.png?quality=50",
    "traced": false
  },
  {
    "id": "hougang-central-gls",
    "name": "Hougang Central GLS",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "99 Years · D19",
    "image": "https://img.singmap.com/upload/broke/a0a87c09a8fa45f1b629fd39f27224c6/7fc6731e8e4a4121a433521c68998c0c/imgs/20251223/22d1d5f3b0a54a0db49fb7cf82ece849.png?quality=50",
    "traced": false
  },
  {
    "id": "hudson-place-residences",
    "name": "Hudson Place Residences",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "327 units · 99 years · D05",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/e80c8fc512304bd7b7969fcf96b00048/imgs/20260401/b109bc2dee40468881810364679b5b71.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "j-den",
    "name": "J'den",
    "district": "D22",
    "area": "Boon Lay / Jurong / Tuas",
    "summary": "368 units · 99 Years · D22",
    "image": "https://img.singmap.com/upload/broke/26a7e3532c1e40c493ccd4d1302549f3/b43a59ee25424f54adb7ea7639a7aee5/imgs/20230928/489fd4dbd98f451a96fa2483da8618aa.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "jansen-house",
    "name": "Jansen House",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "21 units · 999 Years · D19",
    "image": "https://img.singmap.com/upload/broke/5cb3b4b34ffc47d8915a2daa367dbc70/b70f2395f54e4b6b8f8c7d546dd52f21/imgs/20240403/cc6452f50829469aa3cd5053bf43960f.jpg?quality=50",
    "traced": true
  },
  {
    "id": "kallang-riverside",
    "name": "Kallang Riverside",
    "district": "D12",
    "area": "Balestier / Toa Payoh",
    "summary": "212 units · Freehold · D12",
    "image": "https://img.singmap.com/upload/broke/879d04297f8b45e399cae3b85a504ea2/7b9785ffd7f24586a922236b9df4c34d/imgs/7b9785ffd7f24586a922236b9df4c34d.jpg?quality=50",
    "traced": false
  },
  {
    "id": "kassia",
    "name": "Kassia",
    "district": "D17",
    "area": "Loyang / Changi",
    "summary": "276 units · Freehold · D17",
    "image": "https://img.singmap.com/upload/broke/2ee6265311894f32b0d5dbf26a647c41/ad0b6595310b4a0e9bcf1811adab01d1/imgs/20240612/543f1a0a6ecb405282703d54a9e97008.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "keystone-mandai",
    "name": "Keystone @ Mandai",
    "district": "D25",
    "area": "Admiralty / Woodlands",
    "summary": "69 units · Freehold · D25",
    "image": "https://img.singmap.com/upload/broke/6001d53b4156427eb60efedd0e9f4efa/6e09010b103d483cac8ab281bc4a35da/imgs/20251120/5bbb9765b8ef450fb1fc80de95dc8014.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "kovan-jewel",
    "name": "Kovan Jewel",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "34 units · Freehold · D19",
    "image": "https://img.singmap.com/upload/broke/fa3c623bfa964b5fbf83c76dd87deb57/74375cc798c642e991b052bb63b41961/imgs/20221114/2ca8f8d984a74359804321f9260f7124.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "lentor-gardens-residences",
    "name": "Lentor Gardens Residences",
    "district": "D26",
    "area": "Mandai / Upper Thomson",
    "summary": "499 units · 99 Years · D26",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/02a030d8f3ca4ed1b2093e94e3b31115/imgs/20260430/8ece4bbe5c3c4541ab1c5fb4ef0eeeed.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "lentoria",
    "name": "Lentoria",
    "district": "D26",
    "area": "Mandai / Upper Thomson",
    "summary": "267 units · 99 Years · D26",
    "image": "https://img.singmap.com/upload/broke/652323137b984229919afbade2d2b49a/e0d7efea415743a79d08cda8de572c09/imgs/20240105/70d953020aba4d88ac213e301a5b7809.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "lloyd-sixtyfive",
    "name": "Lloyd SixtyFive",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "76 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/c16b84966acc46c6ba69dc2a6291d711/7c16f58f4e8f4474b1e37f70bb57b236/imgs/7c16f58f4e8f4474b1e37f70bb57b236.jpg?quality=50",
    "traced": true
  },
  {
    "id": "lucerne-grand",
    "name": "Lucerne Grand",
    "district": "D22",
    "area": "Boon Lay / Jurong / Tuas",
    "summary": "570 units · 99 Years · D22",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/adf9b59f73ba40cc85938836a28d4037/imgs/20260807/47821877cc854ff58fa76a5624cb4bf1.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "lucida",
    "name": "Lucida",
    "district": "D11",
    "area": "Newton / Novena",
    "summary": "2 units · Freehold · D11",
    "image": "https://img.singmap.com/upload/broke/19541e9bb12d48e7a172283c3f52008f/2e12d01c73fc4def9f4926f3221cae27/imgs/20240910/b80881efb0af40548ba4f31ca4109fa8.jpg?quality=50",
    "traced": false
  },
  {
    "id": "lucky-plaza",
    "name": "Lucky Plaza",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "9 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/2bb941dfc39445998b241147df411af3/7cc8e11b4fa94ab0b26f9ee46133142f/imgs/20260109/a87790adf1cf419aa2bacc6e70d7a08b.jpg?quality=50",
    "traced": false
  },
  {
    "id": "lumiere",
    "name": "Lumiere",
    "district": "D02",
    "area": "Chinatown / Tanjong Pagar",
    "summary": "43 units · 99 Years · D02",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/cfe2e06d0bbf4406ae9b7a2a31ee5385/imgs/20241023/b14161502b2a4b53975a308c356c6462.jpg?quality=50",
    "traced": false
  },
  {
    "id": "meyer-blue",
    "name": "Meyer Blue",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "226 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/83b9b826f1f0445ca23b38813aea6358/imgs/20241128/f516103acfe04d6190bfe85b1cecdcfa.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "midtown-bay",
    "name": "Midtown Bay",
    "district": "D07",
    "area": "Beach Road / Bugis / Rochor",
    "summary": "219 units · 99 Years · D07",
    "image": "https://img.singmap.com/upload/broke/4a789c5dccda41b099ee2b217508d541/0988f8aa42bf469c83868349e1b637b7/imgs/2010e12088ae4b8691521cfc5d4c7e69.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "miltonia-close",
    "name": "Miltonia Close",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "99 Years · D27",
    "image": "https://img.singmap.com/upload/broke/da3d9f7796fb41409a7febecd684da42/b83a142f417049e58c49b5be22ab0cea/imgs/20260511/8facb8ed6a1942d498f0b8757dae57dd.png?quality=50",
    "traced": false
  },
  {
    "id": "narra-residences",
    "name": "Narra Residences",
    "district": "D23",
    "area": "Bukit Batok / Bukit Panjang",
    "summary": "540 units · 99 Years · D23",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/030fee210b074a86a512f1f6cfaf62b6/imgs/20251108/e438272f45064341a4f894fe9af71b3c.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "nava-grove",
    "name": "Nava Grove",
    "district": "D21",
    "area": "Clementi / Upper Bukit Timah",
    "summary": "552 units · 99 Years · D21",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/4a25b483869c44f38fad81c15c945c4f/imgs/20241017/9e1f674dc7a14b9ab2ea1a020534a676.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "newport-residences",
    "name": "Newport Residences",
    "district": "D02",
    "area": "Chinatown / Tanjong Pagar",
    "summary": "246 units · Freehold · D02",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/89abbcafcb6d4b85a543d4131a5148fb/imgs/20251106/bc7b96e8909e447280f74beb594c2d88.png?quality=50",
    "traced": true
  },
  {
    "id": "nim-collection",
    "name": "Nim Collection",
    "district": "D28",
    "area": "Seletar / Yio Chu Kang",
    "summary": "98 units · 99 Years · D28",
    "image": "https://img.singmap.com/upload/broke/c16b84966acc46c6ba69dc2a6291d711/3d1b906a55a44e178b34efb02f6dd867/imgs/3d1b906a55a44e178b34efb02f6dd867.jpg?quality=50",
    "traced": false
  },
  {
    "id": "north-gaia",
    "name": "North Gaia",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "616 units · 99 Years · D27",
    "image": "https://img.singmap.com/upload/broke/0e98949df752401f984325fa8911a1af/e2f59c122d1b47af8d9a734fc79fa467/imgs/20220307/45cbc14feeeb4212ba02b775cc0af0ef.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "norwood-grand",
    "name": "Norwood Grand",
    "district": "D25",
    "area": "Admiralty / Woodlands",
    "summary": "348 units · 99 Years · D25",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/3afb1fde3a244b79bc85e5f39d888ab4/imgs/20240826/fb7960664b6b4d51b6fdec4a1bce82d6.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "ocho",
    "name": "OCHO",
    "district": "D14",
    "area": "Eunos / Geylang / Paya Lebar",
    "summary": "20 units · Freehold · D14",
    "image": "https://img.singmap.com/upload/broke/962385d649ec4d8bb9f92a4999dc01f9/3cb9360aa52c4c4abca691bbb8e5662d/imgs/20250605/96b9b5059a9a488db7ec6cc15d5cbeb8.png?quality=50",
    "traced": false
  },
  {
    "id": "one-chuan-grove",
    "name": "One Chuan Grove",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "99 Years · D19",
    "image": "https://img.singmap.com/upload/broke/0e98949df752401f984325fa8911a1af/f12c41ea74b5463a91ff0c84f7481218/imgs/20251030/95e7bba67183467fb8227ec6d489bd56.jpg?quality=50",
    "traced": false
  },
  {
    "id": "one-marina-gardens",
    "name": "One Marina Gardens",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "937 units · 99 Years · D01",
    "image": "https://img.singmap.com/upload/broke/d4009c115bc14e3298551010fb11dba6/b1d78cceab4d4515a1ec7969ccda74b8/imgs/20250303/bee7d6a3e7c84017930069d475174a3e.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "one-sophia",
    "name": "One Sophia",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "122 units · 99 Years · D09",
    "image": "https://img.singmap.com/upload/broke/70c2bd829c564c96a51d0ee8656dc810/41468c148b10404ba328a64ebc45abdb/imgs/20240906/6b68e928432c439789f206e8bb52c2f7.jpg?quality=50",
    "traced": true
  },
  {
    "id": "parksuites",
    "name": "Parksuites",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "119 units · 99 Years · D10",
    "image": "https://img.singmap.com/upload/broke/2bb941dfc39445998b241147df411af3/cd4698ee608646f28762fcb8bf3b6e42/imgs/20230307/7fde2381bdd840a3b597824807376312.jpg?quality=50",
    "traced": true
  },
  {
    "id": "parktown-residence",
    "name": "Parktown Residence",
    "district": "D18",
    "area": "Pasir Ris / Tampines",
    "summary": "1,193 units · 99 Years · D18",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/af5940a962684cb1ac366e1535d1b7a0/imgs/20250111/ee0da83607514e8ebe10eec760db931f.jpg?quality=50",
    "traced": true
  },
  {
    "id": "penrith",
    "name": "Penrith",
    "district": "D03",
    "area": "Alexandra / Commonwealth",
    "summary": "462 units · 99 years · D03",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/31378b5622d24478bc68a07ddc399c65/imgs/20250917/1d07508fc3144717911295aac2ef3160.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "pinery-residences",
    "name": "Pinery Residences",
    "district": "D18",
    "area": "Pasir Ris / Tampines",
    "summary": "588 units · 99 years · D18",
    "image": "https://img.singmap.com/upload/broke/da3d9f7796fb41409a7febecd684da42/eaf892dde8d345e7b8beea79e9851184/imgs/20260129/256c4cbbc8bf46a2b4494455d2dcbd4c.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "promenade-peak",
    "name": "Promenade Peak",
    "district": "D03",
    "area": "Alexandra / Commonwealth",
    "summary": "596 units · 99 years · D03",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/1917872113dc425797ca4239311a6ee3/imgs/20250627/b747cb1080d7429f89d3a408ff65fc39.png?quality=50",
    "traced": true
  },
  {
    "id": "reignwood-hamilton-scotts",
    "name": "Reignwood Hamilton Scotts",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "56 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/ab4ad26debec4daaba2fee51c73c0abc/2944874e9285475194bd3209b67643be/imgs/86d6c38f9c5f47fdbebd8147573cd69e.jpg?quality=50",
    "traced": false
  },
  {
    "id": "residences-at-emerald-hill",
    "name": "Residences at Emerald Hill",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "25 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/3775da0bb0cb4f758d728c5515860644/imgs/20260702/8da7a202248540729a81f79ccf5b65d8.jpg?quality=50",
    "traced": false
  },
  {
    "id": "river-green",
    "name": "River Green",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "524 units · 99 years · D09",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/26c7f1c04dfa4e7eba1a830c9cd0b3ab/imgs/20250709/961c3a08f2754dcf9acec00dd7451edc.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "river-modern",
    "name": "River Modern",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "455 units · 99 years · D09",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/2bf756a1de0c47808e164704cb191232/imgs/20260130/bc15ac9299964dbb909ba61fa33d2a2c.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "seascape",
    "name": "Seascape",
    "district": "D04",
    "area": "Harbourfront / Telok Blangah",
    "summary": "151 units · 99 Years · D04",
    "image": "https://img.singmap.com/upload/broke/50a486660105417e9ee3f8520112dde7/b68fe53049f5471f9340b8c9d946f7a8/imgs/583a78b84f814aa28c43c97d9c90a060.jpg?quality=50",
    "traced": false
  },
  {
    "id": "sembawang-road-gls",
    "name": "Sembawang Road GLS",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "99 Years · D27",
    "image": "https://img.singmap.com/upload/broke/a4a25c1bd1664eaab4140041c330f202/f62ad7ec239241fa8a8bd10dacaf8291/imgs/20251030/9fa2d318a79d485aac033284fbad6c87.png?quality=50",
    "traced": false
  },
  {
    "id": "shoppes-ascent-456",
    "name": "Shoppes @ Ascent 456",
    "district": "D12",
    "area": "Balestier / Toa Payoh",
    "summary": "16 units · Freehold · D12",
    "image": "https://img.singmap.com/upload/broke/a28fa9fe9ec34cc8a3bd019edf8d4c1e/daa27bcdbfc54e32a8886066a449af7b/imgs/20240926/5ae1ca6e1e4747e8b805dc2d8deecaa2.jpg?quality=50",
    "traced": false
  },
  {
    "id": "shoppes-sky-eden",
    "name": "Shoppes @ Sky Eden",
    "district": "D16",
    "area": "Bedok / Upper East Coast",
    "summary": "12 units · 99 years · D16",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/1ab69a57c2d44e8da17b31af8888315c/imgs/20260316/734c3c04647442b7ab265305c8770b0a.jpg?quality=50",
    "traced": false
  },
  {
    "id": "skies-miltonia",
    "name": "Skies Miltonia",
    "district": "D27",
    "area": "Sembawang / Yishun",
    "summary": "420 units · 99 Years · D27",
    "image": "https://img.singmap.com/upload/broke/2f604efc567047edb5e7e92d5ec0666b/a49e407ce61345b2b1d462221494bb62/imgs/20230323/fe897f9936624fbab9781ce833a11fff.png?quality=50",
    "traced": true
  },
  {
    "id": "skywaters-residences",
    "name": "Skywaters Residences",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "99 Years · D01",
    "image": "https://img.singmap.com/upload/broke/2ee5faac45e4465f8a811897312e97a4/8bc99f6e4056433e89a47457580df1bc/imgs/20230908/6b3a0aa223d84d8ab44d88e13c8cf840.jpg?quality=50",
    "traced": false
  },
  {
    "id": "smart-food-mandai",
    "name": "Smart Food @ Mandai",
    "district": "D25",
    "area": "Admiralty / Woodlands",
    "summary": "87 units · Freehold · D25",
    "image": "https://img.singmap.com/upload/broke/5f6212befb1d438aa48fc4086ca70f11/5c4904dc405d458f90902a897a051092/imgs/20231212/ebc740a3a95a4b03bf550beaceaa6ecc.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "solano-grand",
    "name": "Solano Grand",
    "district": "D23",
    "area": "Bukit Batok / Bukit Panjang",
    "summary": "99 Years · D23",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/478f87cc6ca64393bc3aea90f798f484/imgs/20251030/534fb2aff8c94286b2a8a684393ce405.jpg?quality=50",
    "traced": false
  },
  {
    "id": "sophia-meadow",
    "name": "Sophia Meadow",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "41 units · Leasehold · D09",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/eadec74ff2a84a8eb85de08de5bb4664/imgs/20260223/0b5fd734407f4f39ab67f368a9c3be35.png?quality=50",
    "traced": true
  },
  {
    "id": "sophia-regency",
    "name": "Sophia Regency",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "38 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/dd809d12f82a407a89d312b05a8a3117/53026e42201248c4a7746947767deb5e/imgs/20221014/49b4ad87515a46068b759ed2c2319df1.png?quality=50",
    "traced": true
  },
  {
    "id": "sora",
    "name": "SORA",
    "district": "D22",
    "area": "Boon Lay / Jurong / Tuas",
    "summary": "440 units · 99 Years · D22",
    "image": "https://img.singmap.com/upload/broke/f66152f7012949a7b9500e668467fad2/5862d7b906c54440828e1269d19bf2fc/imgs/20231019/f97c2bc0c8954186a8b9eceebcc72906.jpg?quality=50",
    "traced": true
  },
  {
    "id": "space-nova",
    "name": "SPACE NOVA",
    "district": "D19",
    "area": "Hougang / Punggol / Sengkang",
    "summary": "47 units · Freehold · D19",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/afac3a972b2949c0be0e89e42e9f2a09/imgs/20260605/9065a7abef9d4202b11a30e3dc4f8f37.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "springleaf-residence",
    "name": "Springleaf Residence",
    "district": "D26",
    "area": "Mandai / Upper Thomson",
    "summary": "941 units · 99 years · D26",
    "image": "https://img.singmap.com/upload/broke/4a789c5dccda41b099ee2b217508d541/997843e71ffa45d08e3f20e2a0fd96ed/imgs/20250804/03032ba31f714c01b9f502c9e82267a2.jpg?quality=50",
    "traced": true
  },
  {
    "id": "terra-hill",
    "name": "Terra Hill",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "270 units · Freehold · D05",
    "image": "https://img.singmap.com/upload/broke/da3d9f7796fb41409a7febecd684da42/655c7d587a7943a2b95bed4d0b4bf182/imgs/20221223/e85177a9de134b69b91ef8899a861c28.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-arcady-at-boon-keng",
    "name": "The Arcady at Boon Keng",
    "district": "D12",
    "area": "Balestier / Toa Payoh",
    "summary": "172 units · Freehold · D12",
    "image": "https://img.singmap.com/upload/broke/022d402e8a4443db8958b3f946be3a0b/81f063c801ef487f8a695b825e20c30c/imgs/20231118/7525867400504a1da6091c839060493a.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-collective-at-one-sophia",
    "name": "The Collective At One Sophia",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "367 units · 99 Years · D09",
    "image": "https://img.singmap.com/upload/broke/70c2bd829c564c96a51d0ee8656dc810/03c7e19648714d9b88e7002ba6d4c0ec/imgs/20241016/37c357a920e345eaaba00a55e6b7861a.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-giverny-residences",
    "name": "The Giverny Residences",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "6 units · Freehold · D10",
    "image": "https://img.singmap.com/upload/broke/23f846311ee04507bc9f36b7ab89fb86/47f82c749a9c47bbb84d8d1953f08d45/imgs/20230324/3fd969aa3f9e4244869ce2ef4c56b80a.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "the-golden-mile",
    "name": "The Golden Mile",
    "district": "D07",
    "area": "Beach Road / Bugis / Rochor",
    "summary": "153 units · 99 Years · D07",
    "image": "https://img.singmap.com/upload/broke/2ee5faac45e4465f8a811897312e97a4/e2f907ff467944208e80e85df229b39d/imgs/20241213/2c8f5ab28e4b4afab4fd07b9847c28e9.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "the-green-collection",
    "name": "The Green Collection",
    "district": "D04",
    "area": "Harbourfront / Telok Blangah",
    "summary": "20 units · 99 Years · D04",
    "image": "https://img.singmap.com/upload/broke/2f6c41d76fa44d1a9a0f2796f8504375/27eb97b4b94e47ce8e709d22fe8d4f2c/imgs/20240621/00f136ff45264329bca7605bef671be1.jpg?quality=50",
    "traced": false
  },
  {
    "id": "the-hillshore",
    "name": "The Hillshore",
    "district": "D05",
    "area": "Buona Vista / West Coast",
    "summary": "59 units · Freehold · D05",
    "image": "https://img.singmap.com/upload/broke/ac3faf5162b945229e103d269be4f90d/deac97981cbc41baab577f9cf9f03f33/imgs/20240104/6712037a788c4ebc972403e51c10d351.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-line-tanjong-rhu",
    "name": "The Line @ Tanjong Rhu",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "130 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/607755ee5f6d4ffebbb1d9d1fbcc252d/imgs/607755ee5f6d4ffebbb1d9d1fbcc252d.jpg?quality=50",
    "traced": true
  },
  {
    "id": "the-lumos",
    "name": "The Lumos",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "53 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/fa501c4de3a442878cbc4edd6c90cac4/93910c6ae0e449deada6955c5874aafa/imgs/93910c6ae0e449deada6955c5874aafa.jpg?quality=50",
    "traced": false
  },
  {
    "id": "the-myst",
    "name": "The Myst",
    "district": "D23",
    "area": "Bukit Batok / Bukit Panjang",
    "summary": "408 units · 99 Years · D23",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/29c864ff55404605890dfbee32692362/imgs/20230609/28291b9573124443abe630ca9725816d.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-oceanfront-sentosa-cove",
    "name": "The Oceanfront @ Sentosa Cove",
    "district": "D04",
    "area": "Harbourfront / Telok Blangah",
    "summary": "1 units · 99 Years · D04",
    "image": "https://img.singmap.com/upload/broke/c7cc0e4a3aaf449497f82cd2c97c59d4/307f403e5f6c401eae5c0d1d34c7bebf/imgs/20240513/6230b4e7e49c446588481f658f383262.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "the-oliv",
    "name": "The Oliv",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "8 units · Freehold · D10",
    "image": "https://img.singmap.com/upload/broke/90800fcf94e3445ba99eb38b7d726efd/7032341ad23d4aceb62ded1ea87a166c/imgs/f2bd8647e32f455ea9d91f41d1051b60.jpg?quality=50",
    "traced": false
  },
  {
    "id": "the-orie",
    "name": "The Orie",
    "district": "D12",
    "area": "Balestier / Toa Payoh",
    "summary": "777 units · 99 Years · D12",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/23a0bd1f430c4d55a8bf6fd39fb177b8/imgs/20241203/ecc7353679bd4680971126663042e15a.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-ranz",
    "name": "The Ranz",
    "district": "D08",
    "area": "Farrer Park / Serangoon Road",
    "summary": "14 units · Freehold · D08",
    "image": "https://img.singmap.com/upload/broke/c3ad2c443f7f441ea718ca37d305ef33/828a0cc539e54e7e90dcaee7e5c1f995/imgs/20250803/7ae12ac721e74d7b905ff01a7d44fb65.png?quality=50",
    "traced": false
  },
  {
    "id": "the-residences-at-w-singapore-sentosa-cove",
    "name": "The Residences At W Singapore Sentosa Cove",
    "district": "D04",
    "area": "Harbourfront / Telok Blangah",
    "summary": "228 units · 99 Years · D04",
    "image": "https://img.singmap.com/upload/broke/5e29cd22a7d64d27ba9c41e94e68c2d6/661aa8688a254e52a53146a28d5820fe/imgs/20230203/3ff029e575e24b318f0fec3306418557.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "the-ritz-carlton",
    "name": "The Ritz-Carlton",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "57 units · Freehold · D09",
    "image": "https://img.singmap.com/upload/broke/5ee44bd31df24df9afd2d37cb2c05ef1/84c852f5e4334c808facaf3560bb387a/imgs/29f2ab81007a4911ba8ff25b48a35404.jpg?quality=50",
    "traced": false
  },
  {
    "id": "the-robertson-opus",
    "name": "The Robertson Opus",
    "district": "D09",
    "area": "Orchard / River Valley",
    "summary": "348 units · 999 years · D09",
    "image": "https://img.singmap.com/upload/broke/6533cd747aa945afba657c83e2ed2d9b/6e92774ddc714ac293689aa98e405609/imgs/20250524/e284dd6780864e5b98ed355674128ac2.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "the-sen",
    "name": "The Sen",
    "district": "D21",
    "area": "Clementi / Upper Bukit Timah",
    "summary": "347 units · 99 years · D21",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/70b9d30f47f5447da1d5c4252439fd26/imgs/20250904/d31383adbc7b4dc49c5cbfaed464f758.png?quality=50",
    "traced": true
  },
  {
    "id": "the-shorefront",
    "name": "The Shorefront",
    "district": "D17",
    "area": "Loyang / Changi",
    "summary": "23 units · 999 Years · D17",
    "image": "https://img.singmap.com/upload/broke/ae3d954512b1415780510662dec6b8ff/707b1e5a66b34ba1ae679ae9caa298a7/imgs/20230913/53be4079660e4f1fac687982f25cd38b.jpg?quality=50",
    "traced": false
  },
  {
    "id": "the-venue-shoppes",
    "name": "The Venue Shoppes",
    "district": "D13",
    "area": "Macpherson / Potong Pasir",
    "summary": "10 units · 99 Years · D13",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/39a218d20187411db9c54d949edd17cd/imgs/20240828/199f2c94ea154d7e8a72f735fc742c97.jpg?quality=50",
    "traced": false
  },
  {
    "id": "tmw-maxwell",
    "name": "TMW Maxwell",
    "district": "D02",
    "area": "Chinatown / Tanjong Pagar",
    "summary": "324 units · 99 Years · D02",
    "image": "https://img.singmap.com/upload/broke/70c2bd829c564c96a51d0ee8656dc810/54aec0cc3a7a4a058e10fe7e21a44c17/imgs/20230705/88bea06d50e34dcbbf77d135d09a0ddf.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "trio",
    "name": "TRIO",
    "district": "D08",
    "area": "Farrer Park / Serangoon Road",
    "summary": "15 units · Freehold · D08",
    "image": "https://img.singmap.com/upload/broke/9630042326f643958aac4861dff8609b/aa70f67a979540b591df8451d924b6f3/imgs/cc239db3422f44ba97242df39532e748.jpg?quality=50",
    "traced": true
  },
  {
    "id": "turquoise",
    "name": "Turquoise",
    "district": "D04",
    "area": "Harbourfront / Telok Blangah",
    "summary": "91 units · 99 Years · D04",
    "image": "https://img.singmap.com/upload/broke/50a486660105417e9ee3f8520112dde7/5ebd57bddd8545a2b059cc42a3361642/imgs/309c50f1002949db92cd4e033e426aa5.jpg?quality=50",
    "traced": false
  },
  {
    "id": "union-square-residences",
    "name": "Union Square Residences",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "366 units · 99 Years · D01",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/8799614909f948d280ad127a9f14360a/imgs/20241014/0098a5d9cb834b35a51e8817b9070811.png?quality=50",
    "traced": true
  },
  {
    "id": "upperhouse-at-orchard-boulevard",
    "name": "UPPERHOUSE at Orchard Boulevard",
    "district": "D10",
    "area": "Tanglin / Holland",
    "summary": "301 units · 99 Years · D10",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/7cf72256c81743dfba3986a927ef79e6/imgs/20260612/72885e48f62f4ad3bfe57218eac3c2d3.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "v-on-shenton",
    "name": "V on Shenton .",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "510 units · 99 Years · D01",
    "image": "https://img.singmap.com/upload/broke/d7d56ddcef4d4883acc0a31cbbd72e81/76e1d90c9c7d4ed3959ceb2f29b98858/imgs/76e1d90c9c7d4ed3959ceb2f29b98858.jpg?quality=50",
    "traced": false
  },
  {
    "id": "vela-bay",
    "name": "Vela Bay",
    "district": "D16",
    "area": "Bedok / Upper East Coast",
    "summary": "515 units · 99 Years · D16",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/cf7d4684ea39448697222b2a7d7aeab6/imgs/20260214/7d56259747ab41ff9a6f9ebd3816e03f.jpeg?quality=50",
    "traced": true
  },
  {
    "id": "verde-joo-chiat",
    "name": "Verde Joo Chiat",
    "district": "D15",
    "area": "East Coast / Marine Parade",
    "summary": "18 units · Freehold · D15",
    "image": "https://img.singmap.com/upload/broke/ae48bd89462943ac9dcb38c1b9092765/ebe493a28ec14ba6b966faa7476fa25f/imgs/20260408/acfababf367445e79b55b38415f4ad80.png?quality=50",
    "traced": true
  },
  {
    "id": "villas-greenbank-park",
    "name": "Villas @ Greenbank Park",
    "district": "D21",
    "area": "Clementi / Upper Bukit Timah",
    "summary": "3 units · Freehold · D21",
    "image": "https://img.singmap.com/upload/broke/43f80b9550a14e999f55c9913445741e/9072d5ee72fe4606bdbc6c8f76229272/imgs/20250515/0338ea0069e945ffb8c614cc4dc72154.jpg?quality=50",
    "traced": false
  },
  {
    "id": "villas-old-tampines-road",
    "name": "Villas @ Old Tampines Road",
    "district": "D17",
    "area": "Loyang / Changi",
    "summary": "3 units · Freehold · D17",
    "image": "https://img.singmap.com/upload/broke/43f80b9550a14e999f55c9913445741e/0ae5eb46a9594750831d3c42fdbec970/imgs/20250506/322e2001097f46009575d7731bbdc3d9.png?quality=50",
    "traced": false
  },
  {
    "id": "w-residences-marina-view-singapore",
    "name": "W Residences Marina View - Singapore",
    "district": "D01",
    "area": "Boat Quay / Raffles Place",
    "summary": "683 units · 99 Years · D01",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/5172e27253f14c63b687f97a1ae26c15/imgs/20250604/131b80aa0ee8476da0e9d3c3cb4f0045.jpeg?quality=50",
    "traced": false
  },
  {
    "id": "west-connect-building",
    "name": "West Connect Building",
    "district": "D22",
    "area": "Boon Lay / Jurong / Tuas",
    "summary": "384 units · 30 Years · D22",
    "image": "https://img.singmap.com/upload/broke/d379d488126c4abf9505367876588b57/c3b3b7b232e744c79e1e00a2a9b37eb1/imgs/c3b3b7b232e744c79e1e00a2a9b37eb1.jpg?quality=50",
    "traced": false
  },
  {
    "id": "wynwood-grand",
    "name": "Wynwood Grand",
    "district": "D25",
    "area": "Admiralty / Woodlands",
    "summary": "99 Years · D25",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/adbd4a81ec6c4032b0c6d018860067f8/imgs/20251030/a47cc7d2702c421bbf279442689e5ce7.jpg?quality=50",
    "traced": false
  },
  {
    "id": "zyon-grand",
    "name": "Zyon Grand",
    "district": "D03",
    "area": "Alexandra / Commonwealth",
    "summary": "706 units · 99 years · D03",
    "image": "https://img.singmap.com/upload/broke/2029c11d79004b5e915809fbd6e19f7b/a92578afb30f481ea19b4bf48fffb96b/imgs/20250725/5de223a007e84aecb23c0f283ca26c22.jpeg?quality=50",
    "traced": true
  }
];

/** Loads one project's data file on demand. */
export const autoSpecLoaders: Record<string, () => Promise<{ default: unknown }>> = {
  "21-anderson": () => import("./specs/21-anderson.json"),
  "26-newton": () => import("./specs/26-newton.json"),
  "8-bt": () => import("./specs/8-bt.json"),
  "amberwood-at-holland": () => import("./specs/amberwood-at-holland.json"),
  "arc-380": () => import("./specs/arc-380.json"),
  "ardor-residence": () => import("./specs/ardor-residence.json"),
  "arina-east-residences": () => import("./specs/arina-east-residences.json"),
  "artisan-8": () => import("./specs/artisan-8.json"),
  "atlassia": () => import("./specs/atlassia.json"),
  "aurea": () => import("./specs/aurea.json"),
  "bagnall-haus": () => import("./specs/bagnall-haus.json"),
  "bedok-rise-gls": () => import("./specs/bedok-rise-gls.json"),
  "belgravia-ace": () => import("./specs/belgravia-ace.json"),
  "bloomsbury-residences": () => import("./specs/bloomsbury-residences.json"),
  "canberra-crescent-residences": () => import("./specs/canberra-crescent-residences.json"),
  "canninghill-piers": () => import("./specs/canninghill-piers.json"),
  "cape-royale": () => import("./specs/cape-royale.json"),
  "cecil-place": () => import("./specs/cecil-place.json"),
  "centrium-square": () => import("./specs/centrium-square.json"),
  "chancery-hill-collection": () => import("./specs/chancery-hill-collection.json"),
  "chencharu-close-gls": () => import("./specs/chencharu-close-gls.json"),
  "chuan-park": () => import("./specs/chuan-park.json"),
  "citrine-foodland": () => import("./specs/citrine-foodland.json"),
  "clovelle-of-woodlands": () => import("./specs/clovelle-of-woodlands.json"),
  "coastal-cabana": () => import("./specs/coastal-cabana.json"),
  "ct-foodnex": () => import("./specs/ct-foodnex.json"),
  "ct-gold-macpherson": () => import("./specs/ct-gold-macpherson.json"),
  "dairy-farm-walk-gls": () => import("./specs/dairy-farm-walk-gls.json"),
  "duet-emily": () => import("./specs/duet-emily.json"),
  "dunearn-house": () => import("./specs/dunearn-house.json"),
  "eden-residences-capitol": () => import("./specs/eden-residences-capitol.json"),
  "elta": () => import("./specs/elta.json"),
  "faber-residence": () => import("./specs/faber-residence.json"),
  "forett-at-bukit-timah": () => import("./specs/forett-at-bukit-timah.json"),
  "gate": () => import("./specs/gate.json"),
  "gems-ville": () => import("./specs/gems-ville.json"),
  "gourmet-xchange": () => import("./specs/gourmet-xchange.json"),
  "grand-dunman": () => import("./specs/grand-dunman.json"),
  "grange-1866": () => import("./specs/grange-1866.json"),
  "harrison-food-building": () => import("./specs/harrison-food-building.json"),
  "hougang-central-gls": () => import("./specs/hougang-central-gls.json"),
  "hudson-place-residences": () => import("./specs/hudson-place-residences.json"),
  "j-den": () => import("./specs/j-den.json"),
  "jansen-house": () => import("./specs/jansen-house.json"),
  "kallang-riverside": () => import("./specs/kallang-riverside.json"),
  "kassia": () => import("./specs/kassia.json"),
  "keystone-mandai": () => import("./specs/keystone-mandai.json"),
  "kovan-jewel": () => import("./specs/kovan-jewel.json"),
  "lentor-gardens-residences": () => import("./specs/lentor-gardens-residences.json"),
  "lentoria": () => import("./specs/lentoria.json"),
  "lloyd-sixtyfive": () => import("./specs/lloyd-sixtyfive.json"),
  "lucerne-grand": () => import("./specs/lucerne-grand.json"),
  "lucida": () => import("./specs/lucida.json"),
  "lucky-plaza": () => import("./specs/lucky-plaza.json"),
  "lumiere": () => import("./specs/lumiere.json"),
  "meyer-blue": () => import("./specs/meyer-blue.json"),
  "midtown-bay": () => import("./specs/midtown-bay.json"),
  "miltonia-close": () => import("./specs/miltonia-close.json"),
  "narra-residences": () => import("./specs/narra-residences.json"),
  "nava-grove": () => import("./specs/nava-grove.json"),
  "newport-residences": () => import("./specs/newport-residences.json"),
  "nim-collection": () => import("./specs/nim-collection.json"),
  "north-gaia": () => import("./specs/north-gaia.json"),
  "norwood-grand": () => import("./specs/norwood-grand.json"),
  "ocho": () => import("./specs/ocho.json"),
  "one-chuan-grove": () => import("./specs/one-chuan-grove.json"),
  "one-marina-gardens": () => import("./specs/one-marina-gardens.json"),
  "one-sophia": () => import("./specs/one-sophia.json"),
  "parksuites": () => import("./specs/parksuites.json"),
  "parktown-residence": () => import("./specs/parktown-residence.json"),
  "penrith": () => import("./specs/penrith.json"),
  "pinery-residences": () => import("./specs/pinery-residences.json"),
  "promenade-peak": () => import("./specs/promenade-peak.json"),
  "reignwood-hamilton-scotts": () => import("./specs/reignwood-hamilton-scotts.json"),
  "residences-at-emerald-hill": () => import("./specs/residences-at-emerald-hill.json"),
  "river-green": () => import("./specs/river-green.json"),
  "river-modern": () => import("./specs/river-modern.json"),
  "seascape": () => import("./specs/seascape.json"),
  "sembawang-road-gls": () => import("./specs/sembawang-road-gls.json"),
  "shoppes-ascent-456": () => import("./specs/shoppes-ascent-456.json"),
  "shoppes-sky-eden": () => import("./specs/shoppes-sky-eden.json"),
  "skies-miltonia": () => import("./specs/skies-miltonia.json"),
  "skywaters-residences": () => import("./specs/skywaters-residences.json"),
  "smart-food-mandai": () => import("./specs/smart-food-mandai.json"),
  "solano-grand": () => import("./specs/solano-grand.json"),
  "sophia-meadow": () => import("./specs/sophia-meadow.json"),
  "sophia-regency": () => import("./specs/sophia-regency.json"),
  "sora": () => import("./specs/sora.json"),
  "space-nova": () => import("./specs/space-nova.json"),
  "springleaf-residence": () => import("./specs/springleaf-residence.json"),
  "terra-hill": () => import("./specs/terra-hill.json"),
  "the-arcady-at-boon-keng": () => import("./specs/the-arcady-at-boon-keng.json"),
  "the-collective-at-one-sophia": () => import("./specs/the-collective-at-one-sophia.json"),
  "the-giverny-residences": () => import("./specs/the-giverny-residences.json"),
  "the-golden-mile": () => import("./specs/the-golden-mile.json"),
  "the-green-collection": () => import("./specs/the-green-collection.json"),
  "the-hillshore": () => import("./specs/the-hillshore.json"),
  "the-line-tanjong-rhu": () => import("./specs/the-line-tanjong-rhu.json"),
  "the-lumos": () => import("./specs/the-lumos.json"),
  "the-myst": () => import("./specs/the-myst.json"),
  "the-oceanfront-sentosa-cove": () => import("./specs/the-oceanfront-sentosa-cove.json"),
  "the-oliv": () => import("./specs/the-oliv.json"),
  "the-orie": () => import("./specs/the-orie.json"),
  "the-ranz": () => import("./specs/the-ranz.json"),
  "the-residences-at-w-singapore-sentosa-cove": () => import("./specs/the-residences-at-w-singapore-sentosa-cove.json"),
  "the-ritz-carlton": () => import("./specs/the-ritz-carlton.json"),
  "the-robertson-opus": () => import("./specs/the-robertson-opus.json"),
  "the-sen": () => import("./specs/the-sen.json"),
  "the-shorefront": () => import("./specs/the-shorefront.json"),
  "the-venue-shoppes": () => import("./specs/the-venue-shoppes.json"),
  "tmw-maxwell": () => import("./specs/tmw-maxwell.json"),
  "trio": () => import("./specs/trio.json"),
  "turquoise": () => import("./specs/turquoise.json"),
  "union-square-residences": () => import("./specs/union-square-residences.json"),
  "upperhouse-at-orchard-boulevard": () => import("./specs/upperhouse-at-orchard-boulevard.json"),
  "v-on-shenton": () => import("./specs/v-on-shenton.json"),
  "vela-bay": () => import("./specs/vela-bay.json"),
  "verde-joo-chiat": () => import("./specs/verde-joo-chiat.json"),
  "villas-greenbank-park": () => import("./specs/villas-greenbank-park.json"),
  "villas-old-tampines-road": () => import("./specs/villas-old-tampines-road.json"),
  "w-residences-marina-view-singapore": () => import("./specs/w-residences-marina-view-singapore.json"),
  "west-connect-building": () => import("./specs/west-connect-building.json"),
  "wynwood-grand": () => import("./specs/wynwood-grand.json"),
  "zyon-grand": () => import("./specs/zyon-grand.json"),
};

/** Loads TRM's tracing of the project's site plan, where there is one. */
export const autoTraceLoaders: Record<string, () => Promise<{ default: unknown }>> = {
  "21-anderson": () => import("./traces/21-anderson.json"),
  "8-bt": () => import("./traces/8-bt.json"),
  "amberwood-at-holland": () => import("./traces/amberwood-at-holland.json"),
  "arina-east-residences": () => import("./traces/arina-east-residences.json"),
  "atlassia": () => import("./traces/atlassia.json"),
  "aurea": () => import("./traces/aurea.json"),
  "bagnall-haus": () => import("./traces/bagnall-haus.json"),
  "bloomsbury-residences": () => import("./traces/bloomsbury-residences.json"),
  "canberra-crescent-residences": () => import("./traces/canberra-crescent-residences.json"),
  "chuan-park": () => import("./traces/chuan-park.json"),
  "coastal-cabana": () => import("./traces/coastal-cabana.json"),
  "duet-emily": () => import("./traces/duet-emily.json"),
  "dunearn-house": () => import("./traces/dunearn-house.json"),
  "elta": () => import("./traces/elta.json"),
  "faber-residence": () => import("./traces/faber-residence.json"),
  "forett-at-bukit-timah": () => import("./traces/forett-at-bukit-timah.json"),
  "gems-ville": () => import("./traces/gems-ville.json"),
  "grand-dunman": () => import("./traces/grand-dunman.json"),
  "hudson-place-residences": () => import("./traces/hudson-place-residences.json"),
  "jansen-house": () => import("./traces/jansen-house.json"),
  "kassia": () => import("./traces/kassia.json"),
  "kovan-jewel": () => import("./traces/kovan-jewel.json"),
  "lentor-gardens-residences": () => import("./traces/lentor-gardens-residences.json"),
  "lentoria": () => import("./traces/lentoria.json"),
  "lloyd-sixtyfive": () => import("./traces/lloyd-sixtyfive.json"),
  "lucerne-grand": () => import("./traces/lucerne-grand.json"),
  "meyer-blue": () => import("./traces/meyer-blue.json"),
  "midtown-bay": () => import("./traces/midtown-bay.json"),
  "narra-residences": () => import("./traces/narra-residences.json"),
  "nava-grove": () => import("./traces/nava-grove.json"),
  "newport-residences": () => import("./traces/newport-residences.json"),
  "north-gaia": () => import("./traces/north-gaia.json"),
  "norwood-grand": () => import("./traces/norwood-grand.json"),
  "one-marina-gardens": () => import("./traces/one-marina-gardens.json"),
  "one-sophia": () => import("./traces/one-sophia.json"),
  "parksuites": () => import("./traces/parksuites.json"),
  "parktown-residence": () => import("./traces/parktown-residence.json"),
  "penrith": () => import("./traces/penrith.json"),
  "pinery-residences": () => import("./traces/pinery-residences.json"),
  "promenade-peak": () => import("./traces/promenade-peak.json"),
  "river-green": () => import("./traces/river-green.json"),
  "river-modern": () => import("./traces/river-modern.json"),
  "skies-miltonia": () => import("./traces/skies-miltonia.json"),
  "sophia-meadow": () => import("./traces/sophia-meadow.json"),
  "sophia-regency": () => import("./traces/sophia-regency.json"),
  "sora": () => import("./traces/sora.json"),
  "springleaf-residence": () => import("./traces/springleaf-residence.json"),
  "terra-hill": () => import("./traces/terra-hill.json"),
  "the-arcady-at-boon-keng": () => import("./traces/the-arcady-at-boon-keng.json"),
  "the-collective-at-one-sophia": () => import("./traces/the-collective-at-one-sophia.json"),
  "the-hillshore": () => import("./traces/the-hillshore.json"),
  "the-line-tanjong-rhu": () => import("./traces/the-line-tanjong-rhu.json"),
  "the-myst": () => import("./traces/the-myst.json"),
  "the-orie": () => import("./traces/the-orie.json"),
  "the-robertson-opus": () => import("./traces/the-robertson-opus.json"),
  "the-sen": () => import("./traces/the-sen.json"),
  "tmw-maxwell": () => import("./traces/tmw-maxwell.json"),
  "trio": () => import("./traces/trio.json"),
  "union-square-residences": () => import("./traces/union-square-residences.json"),
  "vela-bay": () => import("./traces/vela-bay.json"),
  "verde-joo-chiat": () => import("./traces/verde-joo-chiat.json"),
  "zyon-grand": () => import("./traces/zyon-grand.json"),
};
