"""Storey counts for HDB blocks around Thomson Reserve.

Usage: python3 scripts/data/hdb-storeys.py

OpenStreetMap often has the footprints of HDB blocks but not their storeys,
so the 3D map drew them as flat outlines. This script takes each block's
highest floor from HDB's "HDB Property Information" dataset on data.gov.sg,
finds the block's address point with OneMap's public search, places it on
the site plan with the same fit as scripts/osm/build-context.py, and writes
src/features/selector/data/thomson-reserve/hdb-blocks.ts. The map layer then
gives each OpenStreetMap footprint that contains a block's point that
block's storeys. Needs data.gov.sg and www.onemap.gov.sg allowed.
"""

import datetime
import importlib.util
import json
import math
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src/features/selector/data/thomson-reserve/hdb-blocks.ts"
DATASET = "d_17f5382f26140b1fdae0ba2ef6239d2f"  # HDB Property Information
TOWNS = ["BH"]  # Bishan: Sin Ming and Bright Hill, north of the site

spec = importlib.util.spec_from_file_location("osm", ROOT / "scripts/osm/build-context.py")
osm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(osm)

STREETS = {"AVE": "AVENUE", "DR": "DRIVE", "RD": "ROAD", "ST": "STREET", "CRES": "CRESCENT", "LOR": "LORONG"}


def get(url, tries=4):
    for i in range(tries):
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                return json.load(r)
        except Exception:
            if i == tries - 1:
                raise
            time.sleep(2 ** i)


def records(town):
    q = urllib.parse.urlencode({"resource_id": DATASET, "filters": json.dumps({"bldg_contract_town": town}), "limit": 2000})
    return get(f"https://data.gov.sg/api/action/datastore_search?{q}")["result"]["records"]


def locate(blk, street):
    words = " ".join(STREETS.get(w, w) for w in street.split())
    q = urllib.parse.urlencode({"searchVal": f"{blk} {words}", "returnGeom": "Y", "getAddrDetails": "Y", "pageNum": 1})
    for hit in get(f"https://www.onemap.gov.sg/api/common/elastic/search?{q}").get("results", []):
        if hit.get("BLK_NO", "").upper() == blk.upper() and words in hit.get("ROAD_NAME", "").upper():
            return float(hit["LATITUDE"]), float(hit["LONGITUDE"])
    return None


def title(street):
    return " ".join(STREETS.get(w, w).capitalize() for w in street.split())


def main():
    rows = []
    for town in TOWNS:
        for r in records(town):
            ll = locate(r["blk_no"], r["street"])
            time.sleep(0.15)
            if not ll:
                print("not found:", r["blk_no"], r["street"])
                continue
            x, y = osm.to_plan(*ll)
            if math.dist((x, y), osm.SITE_CENTRE) > osm.RADIUS_M:
                continue
            rows.append((r["blk_no"], title(r["street"]), int(r["max_floor_lvl"]), r["year_completed"], r["residential"] == "Y", round(x, 1), round(y, 1)))
    rows.sort(key=lambda t: (t[1], t[0]))
    body = ",\n".join(f"  [{json.dumps(b)}, {json.dumps(s)}, {lv}, {yr}, {str(res).lower()}, {x}, {y}]" for b, s, lv, yr, res, x, y in rows)
    OUT.write_text(
        "// Generated by scripts/data/hdb-storeys.py. Do not edit by hand.\n"
        "// Highest floor of each HDB block near the site, from HDB Property\n"
        "// Information (data.gov.sg), placed on the plan at its OneMap address point.\n"
        "//\n"
        "// [block, street, highest floor, year completed, residential, x, y]\n\n"
        f'export const HDB_FETCHED = "{datetime.date.today().isoformat()}";\n\n'
        "export const hdbBlocks: [string, string, number, number, boolean, number, number][] = [\n"
        f"{body},\n];\n"
    )
    print(f"wrote {len(rows)} blocks to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
