"""Turn a rental-contract export (Huttons / URA Realis CSV) into project data.

Usage:
  python3 scripts/data/rentals-from-csv.py RENTALS.csv \
      --project "JadeScape" --export jadescapeRentals \
      --out src/features/selector/data/comparables/jadescape-rentals.ts \
      --source "Huttons rental report (URA Realis, EdgeProp, EcoProp, Huttons)" \
      --as-at 2026-10-03

Expects a header row DATE, AREA (SQFT), RENT, BEDS[, SUBTYPE]; anything
above it (disclaimers) is skipped. Dates like "Aug 2026" become the first of
the month. Area bands like "1,000 - 1,100" are kept as bands, because the
source does not give exact sizes. A blank BEDS stays null: bedroom counts
are never guessed from size.
"""

import argparse
import csv
import datetime
import json
from pathlib import Path


def num(s: str) -> float:
    return float(s.replace("$", "").replace(",", "").strip())


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--project", required=True)
    ap.add_argument("--export", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--as-at", required=True, help="Date the export was produced, YYYY-MM-DD")
    a = ap.parse_args()

    rows = list(csv.reader(open(a.csv, newline="", encoding="utf-8-sig")))
    start = next(i for i, r in enumerate(rows) if r and r[0].strip().upper() == "DATE")
    head = [h.strip().upper() for h in rows[start]]
    col = {name: head.index(name) for name in ("DATE", "AREA (SQFT)", "RENT", "BEDS")}

    out, skipped = [], 0
    for r in rows[start + 1:]:
        if not r or not r[0].strip():
            continue
        try:
            month = datetime.datetime.strptime(r[col["DATE"]].strip(), "%b %Y").date().isoformat()
            lo, hi = (num(x) for x in r[col["AREA (SQFT)"]].split("-"))
            rent = num(r[col["RENT"]])
        except (ValueError, IndexError):
            skipped += 1
            continue
        beds = r[col["BEDS"]].strip()
        out.append([month, int(lo), int(hi), int(rent), int(beds) if beds else None])

    months = sorted(x[0] for x in out)
    no_beds = sum(1 for x in out if x[4] is None)
    body = ",\n  ".join(json.dumps(x).replace("null", "null") for x in out)
    Path(a.out).write_text(
        f"""// {a.project} rental contracts, generated by scripts/data/rentals-from-csv.py.
// Do not edit by hand. {len(out)} contracts, {months[0][:7]} to {months[-1][:7]};
// {no_beds} have no bedroom count and stay unclassified.

import type {{ RentalEvidence }} from "../../model/project";

// [lease month, area band from sq ft, area band to sq ft, monthly rent, bedrooms or null]
type Row = [string, number, number, number, number | null];

const rows: Row[] = [
  {body},
];

export const {a.export}: RentalEvidence = {{
  project: {json.dumps(a.project)},
  records: rows.map(([month, min, max, monthlyRent, bedrooms]) => ({{ month, areaSqft: {{ min, max }}, monthlyRent, bedrooms }})),
  kind: "third-party",
  provenance: {{
    source: {json.dumps(a.source)},
    updated: {json.dumps(a.as_at)},
    status: "verified",
    note: {json.dumps(f"{len(out)} rental contracts signed {months[0][:7]} to {months[-1][:7]}. Sizes are given as 100 sq ft bands. {no_beds} contracts have no bedroom count; they are kept but not assigned a bedroom type.")},
  }},
}};
"""
    )
    print(f"{len(out)} contracts ({no_beds} without bedrooms, {skipped} skipped) -> {a.out}")


if __name__ == "__main__":
    main()
