"""Singapore's planning areas as a light base map for the projects map.

Usage: python3 scripts/data/sg-basemap.py [planning-areas.geojson]

Downloads URA's Master Plan 2019 planning area boundaries (no sea) from
data.gov.sg unless a file is given, simplifies the outlines to about 25 m and
writes src/features/catalogue/data/sg-basemap.ts, with MRT and LRT stations, as SVG paths in metres on a
flat projection centred on Singapore (see PROJECTION in that file). Embedding
the outlines keeps the map working where outside map tiles can't load.
"""

import json
import math
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src/features/catalogue/data/sg-basemap.ts"
DATASET = "d_4765db0e87b9c86336792efe8a1f7a66"  # Master Plan 2019 Planning Area Boundary (No Sea)
MRT_DATASET = "d_b39d3a0871985372d7e1637193335da5"  # LTA MRT Station Exit
LAT0, LON0 = 1.35, 103.82
M_PER_DEG = 111320.0
TOLERANCE_M = 25


def project(lon, lat):
    return ((lon - LON0) * M_PER_DEG * math.cos(math.radians(LAT0)), (LAT0 - lat) * M_PER_DEG)


def simplify(pts, tol):
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    best, idx = 0.0, 0
    for i in range(1, len(pts) - 1):
        d = abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / norm if norm > 1e-9 else math.dist(pts[i], pts[0])
        if d > best:
            best, idx = d, i
    if best <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[: idx + 1], tol)[:-1] + simplify(pts[idx:], tol)


def ring_path(ring):
    pts = simplify([project(lon, lat) for lon, lat, *_ in ring], TOLERANCE_M)
    if len(pts) < 4:
        return ""
    return "M" + "L".join(f"{x:.0f} {y:.0f}" for x, y in pts) + "Z"


def download(dataset):
    ua = {"User-Agent": "Mozilla/5.0 (TRM base map)"}
    req = urllib.request.Request(f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset}/poll-download", headers=ua)
    meta = json.load(urllib.request.urlopen(req, timeout=60))
    return json.load(urllib.request.urlopen(urllib.request.Request(meta["data"]["url"], headers=ua), timeout=120))


def stations():
    """MRT and LRT stations: the middle of each station's exits."""
    exits = {}
    for f in download(MRT_DATASET)["features"]:
        name = f["properties"].get("STATION_NA", "")
        lon, lat = f["geometry"]["coordinates"][:2]
        exits.setdefault(name, []).append((lat, lon))
    out = []
    for name, pts in exits.items():
        label = name.title().replace(" Mrt Station", "").replace(" Lrt Station", " LRT").strip()
        out.append([label, round(sum(p[0] for p in pts) / len(pts), 6), round(sum(p[1] for p in pts) / len(pts), 6)])
    return sorted(out)


def main(src=None):
    data = json.loads(Path(src).read_text()) if src else download(DATASET)
    mrt = stations()
    areas, xs, ys = [], [], []
    for f in data["features"]:
        props, geom = f["properties"], f["geometry"]
        polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        d = "".join(ring_path(poly[0]) for poly in polys)
        for poly in polys:
            for lon, lat, *_ in poly[0]:
                x, y = project(lon, lat)
                xs.append(x)
                ys.append(y)
        name = props.get("PLN_AREA_N", "").title()
        areas.append({"name": name, "region": props.get("REGION_N", "").title(), "d": d})
    areas.sort(key=lambda a: a["name"])
    pad = 1500
    view = [round(min(xs) - pad), round(min(ys) - pad), round(max(xs) - min(xs) + 2 * pad), round(max(ys) - min(ys) + 2 * pad)]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"""// Generated by scripts/data/sg-basemap.py from URA's Master Plan 2019 planning
// area boundaries and LTA's MRT station exits (data.gov.sg, Singapore Open Data
// Licence). Don't edit by hand.

/** Flat projection used by these paths: metres east and south of the centre. */
export const PROJECTION = {{ lat0: {LAT0}, lon0: {LON0}, metresPerDegree: {M_PER_DEG} }};

export const SG_VIEWBOX = {json.dumps(view)} as const;

export const sgPlanningAreas: {{ name: string; region: string; d: string }}[] = {json.dumps(areas, ensure_ascii=False)};

/** MRT and LRT stations (LTA station exits, data.gov.sg): [name, latitude, longitude], at the middle of each station's exits. */
export const sgStations: [string, number, number][] = {json.dumps(mrt, ensure_ascii=False)};
""")
    size = OUT.stat().st_size
    print(f"{len(areas)} planning areas, {len(mrt)} stations, {size / 1024:.0f} KB, written to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
