// Generated by scripts/data/comparables-from-sheet.py from TRM's project sheet:
// the comparable project(s) TRM chose for each project's resale and rental
// records, located on OneMap. Don't edit by hand.

import type { ChosenComparables } from "../../model/project";

export const chosenComparables: ChosenComparables = {
  "source": "TRM's project sheet",
  "checked": "2026-10-06",
  "catalogue": "2026-10-05",
  "projects": [
    {
      "slug": "8-bt",
      "project": "8@BT",
      "comparables": [
        {
          "name": "The Linq @ Beauty World",
          "sheetName": "THE LINQ @ BEAUTY WORLD",
          "address": "118 Upper Bukit Timah Road Singapore 588173",
          "lat": 1.340746,
          "lon": 103.776284,
          "km": 0.09,
          "located": "onemap",
          "underConstruction": false,
          "district": "D21",
          "huttons": {
            "tenure": "Freehold",
            "totalUnits": 173,
            "developer": "BBR Holdings",
            "completion": "2025-07-06",
            "district": "D21"
          }
        }
      ],
      "trmNote": "Similar number of units, projects right next to each other",
      "distanceLimitKm": null
    },
    {
      "slug": "arina-east-residences",
      "project": "Arina East Residences",
      "comparables": [
        {
          "name": "One Meyer",
          "sheetName": "ONE MEYER",
          "address": "1 Meyer Place Singapore 437988",
          "lat": 1.29824,
          "lon": 103.886164,
          "km": 0.24,
          "located": "onemap",
          "underConstruction": false,
          "district": "D15",
          "huttons": {
            "tenure": "Freehold",
            "totalUnits": 66,
            "developer": "SL CAPITAL (5) PTE LTD",
            "completion": "2024-07-26",
            "district": "D15"
          }
        }
      ],
      "trmNote": "Most recent new launch and similar location, but has 10 profitable : 1 unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "bagnall-haus",
      "project": "Bagnall Haus",
      "comparables": [
        {
          "name": "Sceneca Residence",
          "sheetName": "SCENECA RESIDENCE",
          "address": "28 Tanah Merah Kechil Link Singapore 468458",
          "lat": 1.328067,
          "lon": 103.945981,
          "km": 1.33,
          "located": "onemap",
          "underConstruction": false,
          "district": "D16",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 268,
            "developer": "MCC Land (Singapore) Pte Ltd",
            "completion": "2027-12-31",
            "district": "D16"
          }
        }
      ],
      "trmNote": "Sceneca is the closest new launch in scale and profitability",
      "distanceLimitKm": null
    },
    {
      "slug": "bedok-rise-gls",
      "project": "Bedok Rise GLS",
      "comparables": [
        {
          "name": "Sceneca Residence",
          "sheetName": "SCENECA RESIDENCE",
          "address": "28 Tanah Merah Kechil Link Singapore 468458",
          "lat": 1.328067,
          "lon": 103.945981,
          "km": 0.21,
          "located": "onemap",
          "underConstruction": false,
          "district": "D16",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 268,
            "developer": "MCC Land (Singapore) Pte Ltd",
            "completion": "2027-12-31",
            "district": "D16"
          }
        }
      ],
      "trmNote": "Similar number of units, both nearby Tanah Merah MRT",
      "distanceLimitKm": null
    },
    {
      "slug": "bloomsbury-residences",
      "project": "Bloomsbury Residences",
      "comparables": [
        {
          "name": "Commonwealth Towers",
          "sheetName": "COMMONWEALTH TOWERS",
          "address": "230 Commonwealth Avenue Singapore 149739",
          "lat": 1.295734,
          "lon": 103.80603,
          "km": 1.23,
          "located": "onemap",
          "underConstruction": false,
          "district": "D03",
          "huttons": null
        }
      ],
      "trmNote": "Closest recent new launch in terms of location and size",
      "distanceLimitKm": null
    },
    {
      "slug": "canberra-crescent-residences",
      "project": "Canberra Crescent Residences",
      "comparables": [
        {
          "name": "Watergardens @ Canberra",
          "sheetName": "WATERGARDENS @ CANBERRA",
          "address": "57 Canberra Drive Singapore 769330",
          "lat": 1.440857,
          "lon": 103.827823,
          "km": 1.04,
          "located": "onemap",
          "underConstruction": false,
          "district": "D27",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 448,
            "developer": "United Venture Development (2020) Pte Ltd",
            "completion": "2026-06-30",
            "district": "D27"
          }
        }
      ],
      "trmNote": "Similar location and scale",
      "distanceLimitKm": null
    },
    {
      "slug": "canninghill-piers",
      "project": "Canninghill Piers",
      "comparables": [
        {
          "name": "The Imperial",
          "sheetName": "THE IMPERIAL",
          "address": "11 Jalan Rumbia Singapore 239621",
          "lat": 1.294745,
          "lon": 103.842729,
          "km": 0.4,
          "located": "onemap",
          "underConstruction": false,
          "district": "D09",
          "huttons": null
        }
      ],
      "trmNote": "Old condo (2006) but fully profitable at 100+ transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "chencharu-close-gls",
      "project": "Chencharu Close GLS",
      "comparables": [
        {
          "name": "The Estuary",
          "sheetName": "THE ESTUARY",
          "address": "89 Yishun Avenue 1 Singapore 769134",
          "lat": 1.410776,
          "lon": 103.830718,
          "km": 0.68,
          "located": "onemap",
          "underConstruction": false,
          "district": "D27",
          "huttons": null
        }
      ],
      "trmNote": "Old condo (2008) but very nearby and fully profitable at 123 transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "chuan-park",
      "project": "Chuan Park",
      "comparables": [
        {
          "name": "The Scala",
          "sheetName": "THE SCALA",
          "address": "136 Serangoon Avenue 3 Singapore 554476",
          "lat": 1.351407,
          "lon": 103.865405,
          "km": 0.24,
          "located": "onemap",
          "underConstruction": false,
          "district": "D19",
          "huttons": null
        }
      ],
      "trmNote": "Quite an old condo (2013) but fully profitable and the newest in the area",
      "distanceLimitKm": null
    },
    {
      "slug": "clovelle-of-woodlands",
      "project": "Clovelle of Woodlands",
      "comparables": [
        {
          "name": "Twin Fountains",
          "sheetName": "TWIN FOUNTAINS",
          "address": "11 Woodlands Avenue 6 Singapore 738992",
          "lat": 1.430789,
          "lon": 103.799469,
          "km": 0.58,
          "located": "onemap",
          "underConstruction": false,
          "district": "D25",
          "huttons": null
        }
      ],
      "trmNote": "Close to Clovelle of Woodlands and fully profitable at 179 transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "coastal-cabana",
      "project": "Coastal Cabana",
      "comparables": [
        {
          "name": "Pasir Ris 8",
          "sheetName": "PASIR RIS 8",
          "address": "20 Pasir Ris Drive 8 Singapore 519473",
          "lat": 1.374671,
          "lon": 103.949162,
          "km": 0.9,
          "located": "onemap",
          "underConstruction": false,
          "district": "D18",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 487,
            "developer": "Allgreen Properties Ltd & Kerry Properties Ltd",
            "completion": "2026-06-30",
            "district": "D18"
          }
        },
        {
          "name": "Ripple Bay",
          "sheetName": "RIPPLE BAY",
          "address": "2 Pasir Ris Link Singapore 518184",
          "lat": 1.37728,
          "lon": 103.960995,
          "km": 0.45,
          "located": "onemap",
          "underConstruction": false,
          "district": "D18",
          "huttons": null
        }
      ],
      "trmNote": "Pasir Ris 8 - Most recent new launch Ripple Bay - Closer in terms of similar location",
      "distanceLimitKm": null
    },
    {
      "slug": "dairy-farm-walk-gls",
      "project": "Dairy Farm Walk GLS",
      "comparables": [
        {
          "name": "Dairy Farm Residences",
          "sheetName": "DAIRY FARM RESIDENCES",
          "address": "8 Dairy Farm Lane Singapore 677624",
          "lat": 1.366812,
          "lon": 103.774501,
          "km": 0.28,
          "located": "onemap",
          "underConstruction": false,
          "district": "D23",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, profitable ot unprofitable 67:3",
      "distanceLimitKm": null
    },
    {
      "slug": "elta",
      "project": "ELTA",
      "comparables": [
        {
          "name": "The Clement Canopy",
          "sheetName": "THE CLEMENT CANOPY",
          "address": "16 Clementi Avenue 1 Singapore 129960",
          "lat": 1.307332,
          "lon": 103.768479,
          "km": 0.12,
          "located": "onemap",
          "underConstruction": false,
          "district": "D05",
          "huttons": null
        }
      ],
      "trmNote": "Same district and similar area with similar scale, full positive transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "faber-residence",
      "project": "Faber Residence",
      "comparables": [
        {
          "name": "The Clement Canopy",
          "sheetName": "THE CLEMENT CANOPY",
          "address": "16 Clementi Avenue 1 Singapore 129960",
          "lat": 1.307332,
          "lon": 103.768479,
          "km": 2.31,
          "located": "onemap",
          "underConstruction": false,
          "district": "D05",
          "huttons": null
        }
      ],
      "trmNote": "Same district and similar area with similar scale, full positive transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "forett-at-bukit-timah",
      "project": "Forett At Bukit Timah",
      "comparables": [
        {
          "name": "The Reserve Residences",
          "sheetName": "THE RESERVE RESIDENCES",
          "address": "9 Jalan Anak Bukit Singapore 589603",
          "lat": 1.33992,
          "lon": 103.776935,
          "km": 0.94,
          "located": "onemap",
          "underConstruction": true,
          "district": "D21",
          "huttons": null
        }
      ],
      "trmNote": "Similar area",
      "distanceLimitKm": null
    },
    {
      "slug": "grand-dunman",
      "project": "Grand Dunman",
      "comparables": [
        {
          "name": "Liv @ MB",
          "sheetName": "LIV @ MB",
          "address": "114B Arthur Road Singapore 439835",
          "lat": 1.300225,
          "lon": 103.888403,
          "km": 0.96,
          "located": "onemap",
          "underConstruction": false,
          "district": "D15",
          "huttons": {
            "tenure": "99 Year",
            "totalUnits": 298,
            "developer": "Bukit Sembawang Land Pte Ltd",
            "completion": "2024-12-31",
            "district": "D15"
          }
        }
      ],
      "trmNote": "Fully profitable and similar location",
      "distanceLimitKm": null
    },
    {
      "slug": "hougang-central-gls",
      "project": "Hougang Central GLS",
      "comparables": [
        {
          "name": "Riverfront Residences",
          "sheetName": "RIVERFRONT RESIDENCES",
          "address": "47 Hougang Avenue 7 Singapore 533816",
          "lat": 1.371404,
          "lon": 103.899645,
          "km": 0.81,
          "located": "onemap",
          "underConstruction": false,
          "district": "D19",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 1472,
            "developer": "Rio Casa Venture Pte Ltd",
            "completion": "2024-12-31",
            "district": "D19"
          }
        }
      ],
      "trmNote": "Fully profitable at 500+ transactions, in Hougang area too",
      "distanceLimitKm": null
    },
    {
      "slug": "hudson-place-residences",
      "project": "Hudson Place Residences",
      "comparables": [
        {
          "name": "Commonwealth Towers",
          "sheetName": "COMMONWEALTH TOWERS",
          "address": "230 Commonwealth Avenue Singapore 149739",
          "lat": 1.295734,
          "lon": 103.80603,
          "km": 1.23,
          "located": "onemap",
          "underConstruction": false,
          "district": "D03",
          "huttons": null
        }
      ],
      "trmNote": "Closest recent new launch in terms of location and size",
      "distanceLimitKm": null
    },
    {
      "slug": "j-den",
      "project": "J'den",
      "comparables": [
        {
          "name": "J Gateway",
          "sheetName": "J Gateway",
          "address": "2 Gateway Drive Singapore 608533",
          "lat": 1.335557,
          "lon": 103.742417,
          "km": 0.33,
          "located": "onemap",
          "underConstruction": false,
          "district": "D22",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, 150:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "kassia",
      "project": "Kassia",
      "comparables": [
        {
          "name": "Parc Komo",
          "sheetName": "PARC KOMO",
          "address": "967 Upper Changi Road North Singapore 507666",
          "lat": 1.361006,
          "lon": 103.969182,
          "km": 0.56,
          "located": "onemap",
          "underConstruction": false,
          "district": "D17",
          "huttons": {
            "tenure": "Freehold",
            "totalUnits": 276,
            "developer": "CEL Real Estate Development Pte Ltd",
            "completion": "2023-06-04",
            "district": "D17"
          }
        }
      ],
      "trmNote": "Similar location & size, and fully profitable at 43 transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "lentor-gardens-residences",
      "project": "Lentor Gardens Residences",
      "comparables": [
        {
          "name": "Lentor Modern",
          "sheetName": "LENTOR MODERN",
          "address": "3 Lentor Central Singapore 788888",
          "lat": 1.386071,
          "lon": 103.83392,
          "km": 0.32,
          "located": "onemap",
          "underConstruction": false,
          "district": "D26",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 605,
            "developer": "GuocoLand",
            "completion": "2026-06-30",
            "district": "D26"
          }
        }
      ],
      "trmNote": "Same location, 61:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "lentoria",
      "project": "Lentoria",
      "comparables": [
        {
          "name": "Lentor Modern",
          "sheetName": "LENTOR MODERN",
          "address": "7 Lentor Central Singapore 788890",
          "lat": 1.385241,
          "lon": 103.835184,
          "km": 0.41,
          "located": "onemap",
          "underConstruction": false,
          "district": "D26",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 605,
            "developer": "GuocoLand",
            "completion": "2026-06-30",
            "district": "D26"
          }
        }
      ],
      "trmNote": "Same location, 61:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "lucerne-grand",
      "project": "Lucerne Grand",
      "comparables": [
        {
          "name": "Lake Grande",
          "sheetName": "LAKE GRANDE",
          "address": "6 Jurong Lake Link Singapore 648159",
          "lat": 1.345599,
          "lon": 103.724023,
          "km": 0.5,
          "located": "onemap",
          "underConstruction": false,
          "district": "D22",
          "huttons": null
        }
      ],
      "trmNote": "Fully profitable and similar location with the same views",
      "distanceLimitKm": null
    },
    {
      "slug": "meyer-blue",
      "project": "Meyer Blue",
      "comparables": [
        {
          "name": "Amber Park",
          "sheetName": "AMBER PARK",
          "address": "16 Amber Gardens Singapore 439961",
          "lat": 1.300378,
          "lon": 103.899209,
          "km": 0.94,
          "located": "onemap",
          "underConstruction": false,
          "district": "D15",
          "huttons": {
            "tenure": "Freehold",
            "totalUnits": 592,
            "developer": "Aquarius Properties Pte Ltd",
            "completion": "2023-07-01",
            "district": "D15"
          }
        }
      ],
      "trmNote": "Similar location, fully profitable at 87 transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "miltonia-close",
      "project": "Miltonia Close",
      "comparables": [
        {
          "name": "The Criterion",
          "sheetName": "THE CRITERION",
          "address": "9 Yishun Street 51 Singapore 767970",
          "lat": 1.418485,
          "lon": 103.846109,
          "km": 0.42,
          "located": "onemap",
          "underConstruction": false,
          "district": "D27",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, and also fully profitable at 240+ transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "narra-residences",
      "project": "Narra Residences",
      "comparables": [
        {
          "name": "The Reserve Residences",
          "sheetName": "THE RESERVE RESIDENCES",
          "address": "15 Jalan Anak Bukit Singapore 589770",
          "lat": 1.340842,
          "lon": 103.777683,
          "km": 3.0,
          "located": "onemap",
          "underConstruction": true,
          "district": "D21",
          "huttons": null
        }
      ],
      "trmNote": "Similar location and scale",
      "distanceLimitKm": null
    },
    {
      "slug": "nava-grove",
      "project": "Nava Grove",
      "comparables": [
        {
          "name": "The Reserve Residences",
          "sheetName": "THE RESERVE RESIDENCES",
          "address": "7 Jalan Anak Bukit Singapore 589602",
          "lat": 1.33926,
          "lon": 103.7774,
          "km": 2.22,
          "located": "onemap",
          "underConstruction": true,
          "district": "D21",
          "huttons": null
        }
      ],
      "trmNote": "Similar location and scale",
      "distanceLimitKm": null
    },
    {
      "slug": "north-gaia",
      "project": "North Gaia",
      "comparables": [
        {
          "name": "Symphony Suites",
          "sheetName": "SYMPHONY SUITES",
          "address": "17 Yishun Close Singapore 768012",
          "lat": 1.435321,
          "lon": 103.84475,
          "km": 0.08,
          "located": "onemap",
          "underConstruction": false,
          "district": "D27",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, fully profitable at 244 transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "norwood-grand",
      "project": "Norwood Grand",
      "comparables": [
        {
          "name": "Parc Rosewood",
          "sheetName": "PARC ROSEWOOD",
          "address": "75 Rosewood Drive Singapore 737785",
          "lat": 1.428678,
          "lon": 103.786351,
          "km": 0.5,
          "located": "onemap",
          "underConstruction": false,
          "district": "D25",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, and best profit ratio at 210:5 profitable to unprofitable transactions",
      "distanceLimitKm": null
    },
    {
      "slug": "one-chuan-grove",
      "project": "One Chuan Grove",
      "comparables": [
        {
          "name": "The Scala",
          "sheetName": "THE SCALA",
          "address": "138 Serangoon Avenue 3 Singapore 554475",
          "lat": 1.351142,
          "lon": 103.865117,
          "km": 0.64,
          "located": "onemap",
          "underConstruction": false,
          "district": "D19",
          "huttons": null
        }
      ],
      "trmNote": "Quite an old condo (2013) but fully profitable and the newest in the area",
      "distanceLimitKm": null
    },
    {
      "slug": "one-marina-gardens",
      "project": "One Marina Gardens",
      "comparables": [
        {
          "name": "The Sail @ Marina Bay",
          "sheetName": "THE SAIL @ MARINA BAY",
          "address": "2 Marina Boulevard Singapore 018987",
          "lat": 1.280769,
          "lon": 103.852659,
          "km": 1.27,
          "located": "onemap",
          "underConstruction": false,
          "district": "D01",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, best profit ratio nearby at 229:17 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "parktown-residence",
      "project": "Parktown Residence",
      "comparables": [
        {
          "name": "Treasure at Tampines",
          "sheetName": "TREASURE AT TAMPINES",
          "address": "1 Tampines Lane Singapore 528482",
          "lat": 1.345056,
          "lon": 103.946755,
          "km": 2.61,
          "located": "onemap",
          "underConstruction": false,
          "district": "D18",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 2203,
            "developer": "Sim Lian (Treasure) Pte. Ltd.",
            "completion": "2024-12-31",
            "district": "D18"
          }
        }
      ],
      "trmNote": "both mega developments, also at D18",
      "distanceLimitKm": null
    },
    {
      "slug": "penrith",
      "project": "Penrith",
      "comparables": [
        {
          "name": "Stirling Residences",
          "sheetName": "STIRLING RESIDENCES",
          "address": "21 Stirling Road Singapore 148960",
          "lat": 1.292055,
          "lon": 103.805546,
          "km": 0.56,
          "located": "onemap",
          "underConstruction": false,
          "district": "D03",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 1259,
            "developer": "Nanshan Group Singapore & Logan Property Holdings",
            "completion": "2022-05-30",
            "district": "D03"
          }
        }
      ],
      "trmNote": "Extremely high profitability ratio",
      "distanceLimitKm": null
    },
    {
      "slug": "pinery-residences",
      "project": "Pinery Residences",
      "comparables": [
        {
          "name": "Parc Central Residences",
          "sheetName": "PARC CENTRAL RESIDENCES",
          "address": "123 Tampines Street 86 Singapore 528515",
          "lat": 1.355714,
          "lon": 103.930283,
          "km": 1.6,
          "located": "onemap",
          "underConstruction": false,
          "district": "D18",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 700,
            "developer": "Hoi Hup Sunway Tampines J.V. Pte Ltd",
            "completion": "2023-09-30",
            "district": "D18"
          }
        }
      ],
      "trmNote": "At Tampines West too, all profitable",
      "distanceLimitKm": null
    },
    {
      "slug": "promenade-peak",
      "project": "Promenade Peak",
      "comparables": [
        {
          "name": "Irwell Hill Residences",
          "sheetName": "IRWELL HILL RESIDENCES",
          "address": "6 Irwell Hill Singapore 239590",
          "lat": 1.296669,
          "lon": 103.831613,
          "km": 0.56,
          "located": "onemap",
          "underConstruction": false,
          "district": "D09",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 540,
            "developer": "CDL Perseus Pte. Ltd.",
            "completion": "2025-12-31",
            "district": "D09"
          }
        }
      ],
      "trmNote": "Similar location and new, good profitability ratio at 42:3 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "sembawang-road-gls",
      "project": "Sembawang Road GLS",
      "comparables": [
        {
          "name": "Watergardens @ Canberra",
          "sheetName": "WATERGARDENS @ CANBERRA",
          "address": "41 Canberra Drive Singapore 769322",
          "lat": 1.439896,
          "lon": 103.827181,
          "km": 0.39,
          "located": "onemap",
          "underConstruction": false,
          "district": "D27",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 448,
            "developer": "United Venture Development (2020) Pte Ltd",
            "completion": "2026-06-30",
            "district": "D27"
          }
        }
      ],
      "trmNote": "Similar location and scale",
      "distanceLimitKm": null
    },
    {
      "slug": "solano-grand",
      "project": "Solano Grand",
      "comparables": [
        {
          "name": "Chestervale",
          "sheetName": "CHESTERVALE",
          "address": "37 Bangkit Road Singapore 679976",
          "lat": 1.379001,
          "lon": 103.774086,
          "km": 1.74,
          "located": "onemap",
          "underConstruction": false,
          "district": "D23",
          "huttons": null
        }
      ],
      "trmNote": "Super old condo (1999) but was also an EC and fully profitable at 51 transactions.",
      "distanceLimitKm": null
    },
    {
      "slug": "sora",
      "project": "SORA",
      "comparables": [
        {
          "name": "Lake Grande",
          "sheetName": "LAKE GRANDE",
          "address": "2 Jurong Lake Link Singapore 648157",
          "lat": 1.345474,
          "lon": 103.724623,
          "km": 1.31,
          "located": "onemap",
          "underConstruction": false,
          "district": "D22",
          "huttons": null
        }
      ],
      "trmNote": "Similar location and views",
      "distanceLimitKm": null
    },
    {
      "slug": "springleaf-residence",
      "project": "Springleaf Residence",
      "comparables": [
        {
          "name": "Lentor Modern",
          "sheetName": "LENTOR MODERN",
          "address": "3 Lentor Central Singapore 788888",
          "lat": 1.386071,
          "lon": 103.83392,
          "km": 2.16,
          "located": "onemap",
          "underConstruction": false,
          "district": "D26",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 605,
            "developer": "GuocoLand",
            "completion": "2026-06-30",
            "district": "D26"
          }
        }
      ],
      "trmNote": "Closeby in location, 61:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "terra-hill",
      "project": "Terra Hill",
      "comparables": [
        {
          "name": "Kent Ridge Hill Residences",
          "sheetName": "KENT RIDGE HILL RESIDENCES",
          "address": "56E South Buona Vista Road Singapore 118193",
          "lat": 1.280804,
          "lon": 103.790777,
          "km": 0.42,
          "located": "onemap",
          "underConstruction": false,
          "district": "D05",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 548,
            "developer": "Oxley Spinel Pte Ltd",
            "completion": "2024-12-31",
            "district": "D05"
          }
        }
      ],
      "trmNote": "Closeby in location, fully profitable at 106 transactions.",
      "distanceLimitKm": null
    },
    {
      "slug": "the-arcady-at-boon-keng",
      "project": "The Arcady at Boon Keng",
      "comparables": [
        {
          "name": "Eight Riversuites",
          "sheetName": "EIGHT RIVERSUITES",
          "address": "20 Whampoa East Singapore 338526",
          "lat": 1.321806,
          "lon": 103.863969,
          "km": 0.15,
          "located": "onemap",
          "underConstruction": false,
          "district": "D12",
          "huttons": null
        }
      ],
      "trmNote": "same location, 259:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "the-myst",
      "project": "The Myst",
      "comparables": [
        {
          "name": "Dairy Farm Residences",
          "sheetName": "DAIRY FARM RESIDENCES",
          "address": "8 Dairy Farm Lane Singapore 677624",
          "lat": 1.366812,
          "lon": 103.774501,
          "km": 1.39,
          "located": "onemap",
          "underConstruction": false,
          "district": "D23",
          "huttons": null
        }
      ],
      "trmNote": "Similar location, profitable ot unprofitable 67:3",
      "distanceLimitKm": null
    },
    {
      "slug": "the-orie",
      "project": "The Orie",
      "comparables": [
        {
          "name": "Gem Residences",
          "sheetName": "GEM RESIDENCES",
          "address": "3 Lorong 5 Toa Payoh Singapore 319459",
          "lat": 1.339338,
          "lon": 103.851225,
          "km": 0.16,
          "located": "onemap",
          "underConstruction": false,
          "district": "D12",
          "huttons": null
        }
      ],
      "trmNote": "Close location and new, with high profitability ratio of 186:1 of profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "the-sen",
      "project": "The Sen",
      "comparables": [
        {
          "name": "The Reserve Residences",
          "sheetName": "THE RESERVE RESIDENCES",
          "address": "9 Jalan Anak Bukit Singapore 589603",
          "lat": 1.33992,
          "lon": 103.776935,
          "km": 1.34,
          "located": "onemap",
          "underConstruction": true,
          "district": "D21",
          "huttons": null
        }
      ],
      "trmNote": "Similar location",
      "distanceLimitKm": null
    },
    {
      "slug": "thomson-reserve",
      "project": "Thomson Reserve",
      "comparables": [
        {
          "name": "Jadescape",
          "sheetName": "JADESCAPE",
          "address": "16 Shunfu Road Singapore 575749",
          "lat": 1.351815,
          "lon": 103.838298,
          "km": 0.99,
          "located": "onemap",
          "underConstruction": false,
          "district": "D20",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 1206,
            "developer": "Qingjian Realty (Marymount) Pte Ltd",
            "completion": "2023-01-09",
            "district": "D20"
          }
        }
      ],
      "trmNote": null,
      "distanceLimitKm": null
    },
    {
      "slug": "tmw-maxwell",
      "project": "TMW Maxwell",
      "comparables": [
        {
          "name": "Icon",
          "sheetName": "ICON",
          "address": "10 Gopeng Street Singapore 078878",
          "lat": 1.27517,
          "lon": 103.844496,
          "km": 0.46,
          "located": "onemap",
          "underConstruction": false,
          "district": "D02",
          "huttons": null
        }
      ],
      "trmNote": "Old condo (2007) but the best profitability ratio of 126:3 profitable to unprofitable in the area",
      "distanceLimitKm": null
    },
    {
      "slug": "union-square-residences",
      "project": "Union Square Residences",
      "comparables": [
        {
          "name": "One Pearl Bank",
          "sheetName": "ONE PEARL BANK",
          "address": "1 Pearl Bank Singapore 169016",
          "lat": 1.282961,
          "lon": 103.839815,
          "km": 0.71,
          "located": "onemap",
          "underConstruction": false,
          "district": "D03",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 774,
            "developer": "CapitaLand",
            "completion": "2024-12-31",
            "district": "D03"
          }
        }
      ],
      "trmNote": "Very recent condo but profitable to unprofitable ratio is 53:11",
      "distanceLimitKm": null
    },
    {
      "slug": "vela-bay",
      "project": "Vela Bay",
      "comparables": [
        {
          "name": "Costa del Sol",
          "sheetName": "COSTA DEL SOL",
          "address": "82 Bayshore Road Singapore 469993",
          "lat": 1.311995,
          "lon": 103.940273,
          "km": 0.13,
          "located": "onemap",
          "underConstruction": false,
          "district": "D16",
          "huttons": null
        }
      ],
      "trmNote": "Very old condo (2004) but fully profitable and same location",
      "distanceLimitKm": null
    },
    {
      "slug": "wynwood-grand",
      "project": "Wynwood Grand",
      "comparables": [
        {
          "name": "Bellewoods",
          "sheetName": "BELLEWOODS",
          "address": "120 Woodlands Avenue 5 Singapore 739020",
          "lat": 1.431428,
          "lon": 103.800674,
          "km": 1.2,
          "located": "onemap",
          "underConstruction": false,
          "district": "D25",
          "huttons": null
        }
      ],
      "trmNote": "Similar location and both are ECs, and high profitablity ratio of 213:1 profitable to unprofitable",
      "distanceLimitKm": null
    },
    {
      "slug": "zyon-grand",
      "project": "Zyon Grand",
      "comparables": [
        {
          "name": "Irwell Hill Residences",
          "sheetName": "IRWELL HILL RESIDENCES",
          "address": "6 Irwell Hill Singapore 239590",
          "lat": 1.296669,
          "lon": 103.831613,
          "km": 0.66,
          "located": "onemap",
          "underConstruction": false,
          "district": "D09",
          "huttons": {
            "tenure": "99 Years",
            "totalUnits": 540,
            "developer": "CDL Perseus Pte. Ltd.",
            "completion": "2025-12-31",
            "district": "D09"
          }
        }
      ],
      "trmNote": "Similar location and new, good profitability ratio at 42:3 profitable to unprofitable",
      "distanceLimitKm": null
    }
  ]
};
