// Generated by scripts/huttons/sync-alternatives.py from the Huttons New Launch API
// on 2026-10-05. Don't edit by hand; run the script again to refresh.

import type { AlternativeUnitType } from "../../model/project";

export const alternativesSync: { source: string; fetched: string; projects: Record<string, { totalUnits: number | null; unitTypes: AlternativeUnitType[] }> } = {
  source: "Huttons New Launch API",
  fetched: "2026-10-05",
  projects: {
  "Lentor Gardens Residences": {
    "totalUnits": 499,
    "unitTypes": [
      {
        "bedrooms": 2,
        "type": "2BR Premium",
        "sizeSqft": {
          "min": 646,
          "max": 678
        },
        "fromPrice": 1571300,
        "unitsLeft": 32
      },
      {
        "bedrooms": 2,
        "type": "2BR Premium (HS)",
        "sizeSqft": {
          "min": 689,
          "max": 689
        },
        "fromPrice": 1705500,
        "unitsLeft": 1
      },
      {
        "bedrooms": 2,
        "type": "2BR + Study",
        "sizeSqft": {
          "min": 732,
          "max": 732
        },
        "fromPrice": 1715000,
        "unitsLeft": 102
      },
      {
        "bedrooms": 3,
        "type": "3BR Premium + Study",
        "sizeSqft": {
          "min": 969,
          "max": 969
        },
        "fromPrice": 2221400,
        "unitsLeft": 6
      },
      {
        "bedrooms": 3,
        "type": "3BR Premium",
        "sizeSqft": {
          "min": 1001,
          "max": 1012
        },
        "fromPrice": 2297500,
        "unitsLeft": 9
      },
      {
        "bedrooms": 4,
        "type": "4BR Compact",
        "sizeSqft": {
          "min": 1184,
          "max": 1184
        },
        "fromPrice": 2738000,
        "unitsLeft": 4
      },
      {
        "bedrooms": 4,
        "type": "4BR Premium",
        "sizeSqft": {
          "min": 1346,
          "max": 1356
        },
        "fromPrice": 3129200,
        "unitsLeft": 32
      },
      {
        "bedrooms": 5,
        "type": "Strata Terrace House",
        "sizeSqft": {
          "min": 1496,
          "max": 1496
        },
        "fromPrice": 3515600,
        "unitsLeft": 3
      }
    ]
  },
  "Lentoria": {
    "totalUnits": 267,
    "unitTypes": [
      {
        "bedrooms": 1,
        "type": "1BR",
        "sizeSqft": {
          "min": 538,
          "max": 538
        },
        "fromPrice": 1308000,
        "unitsLeft": 6
      },
      {
        "bedrooms": 2,
        "type": "2BR",
        "sizeSqft": {
          "min": 700,
          "max": 732
        },
        "fromPrice": 1860000,
        "unitsLeft": 5
      },
      {
        "bedrooms": 3,
        "type": "3BR",
        "sizeSqft": {
          "min": 936,
          "max": 936
        },
        "fromPrice": 2279000,
        "unitsLeft": 3
      }
    ]
  },
  "Springleaf Residence": {
    "totalUnits": 941,
    "unitTypes": [
      {
        "bedrooms": 3,
        "type": "3BR + Study + Utility",
        "sizeSqft": {
          "min": 1259,
          "max": 1259
        },
        "fromPrice": 2732000,
        "unitsLeft": 6
      },
      {
        "bedrooms": 5,
        "type": "5BR",
        "sizeSqft": {
          "min": 1453,
          "max": 1475
        },
        "fromPrice": 3233000,
        "unitsLeft": 8
      }
    ]
  },
  "Chuan Park": {
    "totalUnits": 916,
    "unitTypes": [
      {
        "bedrooms": 3,
        "type": "3BR",
        "sizeSqft": {
          "min": 1206,
          "max": 1227
        },
        "fromPrice": 3234900,
        "unitsLeft": 10
      }
    ]
  }
},
};
