// Generated by scripts/data/hdb-storeys.py. Do not edit by hand.
// Highest floor of each HDB block near the site, from HDB Property
// Information (data.gov.sg), placed on the plan at its OneMap address point.
//
// [block, street, highest floor, year completed, residential, x, y]

export const HDB_FETCHED = "2026-10-05";

export const hdbBlocks: [string, string, number, number, boolean, number, number][] = [
  ["446", "Bright Hill Drive", 10, 1988, true, 402.9, -58.9],
  ["447", "Bright Hill Drive", 23, 1989, true, 345.6, -61.3],
  ["448", "Bright Hill Drive", 12, 1988, true, 289.7, -41.1],
  ["448A", "Bright Hill Drive", 5, 2001, false, 345.8, -7.6],
  ["441", "Sin Ming Avenue", 12, 1988, true, 268.8, -121.4],
  ["442", "Sin Ming Avenue", 22, 1988, true, 310.7, -178.4],
  ["443", "Sin Ming Avenue", 10, 1988, true, 373.0, -159.7],
  ["444", "Sin Ming Avenue", 25, 1988, true, 355.1, -115.2],
  ["445", "Sin Ming Avenue", 12, 1988, true, 292.6, -87.6],
  ["449", "Sin Ming Avenue", 12, 1988, true, 258.2, 32.3],
  ["450", "Sin Ming Avenue", 25, 1988, true, 205.2, 37.1],
  ["451", "Sin Ming Avenue", 11, 1988, true, 165.9, 47.6],
  ["452", "Sin Ming Avenue", 4, 1988, true, 134.2, 65.1],
  ["453", "Sin Ming Avenue", 17, 1988, true, 113.6, 14.4],
  ["454", "Sin Ming Avenue", 12, 1988, true, 167.5, -39.1],
  ["455", "Sin Ming Avenue", 12, 1988, true, 199.6, -12.0],
];
