// The neighbourhood around Thomson Reserve, from OpenStreetMap.
//
// osm-context.ts is generated by scripts/osm/build-context.py, which places
// the map on the developer's site plan (see that script for the fit). Here
// the raw arrays become the map layer for the 3D model, and the taller
// buildings whose storeys the map records become view obstructions.
//
// Heights: OpenStreetMap records storeys, not metres. A storey is taken as
// 2.8–3.2 m, plus up to 3 m of roof structures, measured from road level
// because ground levels around the site are not surveyed. Houses without a
// storey count are drawn at 2 storeys, as the architect's brief describes
// the landed estates; other buildings without one are drawn as low
// footprints only and never used in the analysis.

import type { MapBuilding, MapContext, Obstruction, Point, Provenance } from "../../model/types";
import { OSM_EXTRACT_DATE, osmBuildings, osmGreen, osmRoadLabels, osmRoads, osmWater } from "./osm-context";

export const OSM_CREDIT = "Map data © OpenStreetMap contributors";

const points = (flat: number[]): Point[] => {
  const out: Point[] = [];
  for (let i = 0; i < flat.length; i += 2) out.push({ x: flat[i], y: flat[i + 1] });
  return out;
};

/** Drawn height of one storey, metres. */
const STOREY_M = 3;
const HOUSE_STOREYS = 2;
const UNKNOWN_HEIGHT_M = 2;

const osm = (note: string, status: Provenance["status"] = "estimated"): Provenance => ({
  source: "OpenStreetMap",
  updated: OSM_EXTRACT_DATE,
  status,
  note,
});

const buildings: MapBuilding[] = osmBuildings.map(([levels, kind, label, ring]) => ({
  footprint: points(ring),
  levels,
  label,
  ...(levels !== null
    ? { height: "levels" as const, heightM: levels * STOREY_M }
    : kind === "house"
      ? { height: "assumed" as const, heightM: HOUSE_STOREYS * STOREY_M }
      : { height: "unknown" as const, heightM: UNKNOWN_HEIGHT_M }),
}));

export const thomsonReserveMapContext: MapContext = {
  buildings,
  roads: osmRoads.map(([widthM, , line]) => ({ path: points(line), widthM })),
  green: osmGreen.map(points),
  water: osmWater.map(points),
  credit: OSM_CREDIT,
  provenance: osm(
    "Buildings, roads, parks and water within about 650 m. Placed by the plan's north point and scale bar, Upper Thomson MRT Exit 2 falls within about a metre of the plan's marker. Heights use 2.8–3.2 m a storey plus up to 3 m of roof structures; buildings of 4+ storeys within 450 m are checked as obstructions. Houses without a storey count are drawn at 2 storeys, as the architect's brief describes the landed estates; other buildings without one are drawn as low outlines.",
  ),
};

export const thomsonReserveRoadLabels = osmRoadLabels;

/** Buildings this tall or taller, with a recorded storey count, are checked as view obstructions. */
const MIN_OBSTRUCTION_LEVELS = 4;
/** How far from the site centre a building is still checked, metres. */
const OBSTRUCTION_RADIUS_M = 450;

const centroid = (pts: Point[]): Point => ({
  x: pts.reduce((a, p) => a + p.x, 0) / pts.length,
  y: pts.reduce((a, p) => a + p.y, 0) / pts.length,
});

/** Taller mapped buildings near the site, as obstructions for the view and noise checks. */
export function mapObstructions(siteCentre: Point): Obstruction[] {
  return buildings.flatMap((b, i) => {
    if (b.height !== "levels" || b.levels === null || b.levels < MIN_OBSTRUCTION_LEVELS) return [];
    const c = centroid(b.footprint);
    if (Math.hypot(c.x - siteCentre.x, c.y - siteCentre.y) > OBSTRUCTION_RADIUS_M) return [];
    const storeys = `${b.levels}-storey`;
    return [
      {
        id: `osm-${i}`,
        name: b.label ? `${storeys} block, ${b.label}` : `${storeys} block`,
        kind: "existing-building" as const,
        footprint: b.footprint,
        baseRL: 0,
        topRL: { min: Math.round(b.levels * 2.8), max: Math.round(b.levels * 3.2 + 3) },
        heightProvenance: osm(
          `${b.levels} storeys recorded in OpenStreetMap. Top taken as 2.8–3.2 m a storey plus up to 3 m of roof structures, measured from road level; ground level not surveyed.`,
        ),
        fromMap: true,
      },
    ];
  });
}
